"""Built-in default stack configurations for local and remote environments."""

from __future__ import annotations

import os
from collections.abc import Callable

import yaml

from agentomatic.providers.llm import DEFAULT_OMLX_BASE_URL
from agentomatic.stacks.manager import (
    AuthStackConfig,
    DatabaseStackEntry,
    EmbeddingStackEntry,
    FeaturesStackEntry,
    LLMStackEntry,
    StackConfig,
)

#: Model baked into a freshly scaffolded ``stacks/local.yaml``. Any model your
#: local server has loaded works — this is only the starting value, and it is
#: overridable at scaffold time (see :func:`default_local_model`).
DEFAULT_LOCAL_MODEL = "Qwen3.5-9B-MLX-4bit"

#: Header written above a generated ``local.yaml`` — the file is the first
#: place a user looks when the local model does not answer.
_LOCAL_STACK_HEADER = f"""\
# Local development stack — generated by `agentomatic stack init`.
#
# Talks to an OpenAI-compatible small-model server on your machine. oMLX is the
# default; llama.cpp, vLLM and LM Studio speak the same protocol and need only
# a different `base_url`.
#
#   1. Start your model server (oMLX defaults to port 8000):
#        omlx serve --model <your-model>
#   2. Set `model:` below to whatever that server has loaded.
#   3. The platform's own port must differ from the server's:
#        agentomatic run --port 8001
#
# `base_url` / `api_key` may be left empty — the omlx provider then reads
# OMLX_BASE_URL / OMLX_API_KEY, falling back to {DEFAULT_OMLX_BASE_URL}.
"""


def probe_local_models(base_url: str | None = None, *, timeout: float = 1.5) -> list[str]:
    """List the models an OpenAI-compatible server currently has loaded.

    Every scaffolded project used to hard-code :data:`DEFAULT_LOCAL_MODEL`, so
    a local server holding anything else answered the first invoke with HTTP
    400 (unknown model) — the generated stack was wrong the moment it was
    written. Asking the server what it actually serves removes that mismatch.

    The probe is best-effort and never raises: no server, a slow one, or a
    non-OpenAI endpoint all yield an empty list.

    Args:
        base_url: Server base URL (default: :func:`default_local_base_url`).
        timeout: Per-request timeout in seconds.

    Returns:
        Model identifiers, in the order the server reported them.
    """
    import json
    import urllib.error
    import urllib.request

    url = (base_url or default_local_base_url()).rstrip("/") + "/models"
    try:
        # A localhost model server must not be reached through a proxy, and
        # an ambient HTTP_PROXY would otherwise swallow the request.
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        with opener.open(url, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (urllib.error.URLError, OSError, ValueError, json.JSONDecodeError):
        return []

    entries = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(entries, list):
        return []
    models: list[str] = []
    for entry in entries:
        identifier = entry.get("id") if isinstance(entry, dict) else None
        if isinstance(identifier, str) and identifier.strip():
            models.append(identifier.strip())
    return models


def default_local_model(*, probe: bool = True) -> str:
    """Return the model name to bake into a generated local stack.

    Resolution order: ``AGENTOMATIC_LOCAL_MODEL``, ``OMLX_MODEL``, whatever a
    running local server reports, then :data:`DEFAULT_LOCAL_MODEL`.

    Args:
        probe: Ask a running local server when no env var is set.

    Returns:
        A model identifier, e.g. ``"Qwen3.5-9B-MLX-4bit"``.
    """
    model = os.getenv("AGENTOMATIC_LOCAL_MODEL") or os.getenv("OMLX_MODEL") or ""
    resolved = model.strip().removeprefix("omlx/")
    if resolved:
        return resolved
    if probe:
        detected = probe_local_models()
        if detected:
            return detected[0]
    return DEFAULT_LOCAL_MODEL


def default_local_base_url() -> str:
    """Return the endpoint to bake into a generated local stack.

    Returns:
        ``OMLX_BASE_URL`` when set, else :data:`DEFAULT_OMLX_BASE_URL`.
    """
    return (os.getenv("OMLX_BASE_URL") or "").strip() or DEFAULT_OMLX_BASE_URL


def get_default_local_stack() -> StackConfig:
    """Return a StackConfig for local development.

    Targets a local OpenAI-compatible small-model server (oMLX by default,
    but llama.cpp / vLLM / LM Studio speak the same protocol), SQLite for
    storage, and no authentication — so a freshly scaffolded project runs,
    chats, and trains with no cloud credentials at all.

    Every profile points at the same local model. ``default`` serves agents,
    ``fast`` is for cheap/auxiliary calls, and ``judge`` / ``rewrite`` are the
    roles ``train.py`` looks up when scoring and rewriting prompts.

    Returns:
        A StackConfig pre-configured for local development.
    """

    def _entry(temperature: float) -> LLMStackEntry:
        return LLMStackEntry(
            provider="omlx",
            model=default_local_model(),
            temperature=temperature,
            max_tokens=4096,
            base_url=default_local_base_url(),
            # Local servers ignore the key; leave it empty so the provider
            # can fill it from OMLX_API_KEY when one is actually required.
            api_key="",
            timeout=120.0,
            max_retries=None,
        )

    return StackConfig(
        name="local",
        description=("Local development stack — OpenAI-compatible SLM server (oMLX) + SQLite"),
        llm={
            "default": _entry(0.1),
            "fast": _entry(0.0),
            "judge": _entry(0.0),
            "rewrite": _entry(0.3),
        },
        embedding=EmbeddingStackEntry(
            # Deterministic and dependency-free: RAG scaffolds run without a
            # second server. Swap to ollama/nomic-embed-text (or openai) when
            # retrieval quality starts to matter.
            provider="hash",
            model="hash-256",
            dimension=256,
        ),
        database=DatabaseStackEntry(
            url="sqlite+aiosqlite:///data/platform.db",
            pool_size=5,
            max_overflow=10,
        ),
        features=FeaturesStackEntry(
            enable_streaming=True,
            enable_a2a=True,
            enable_metrics=False,
            enable_rate_limit=False,
            enable_auth=False,
            enable_db=False,
        ),
        auth=AuthStackConfig(
            method="api_key",
            api_key="",
            jwks_url="",
            issuer="",
            audience="",
        ),
    )


def get_default_remote_stack() -> StackConfig:
    """Return a StackConfig for cloud / remote deployment.

    Uses OpenAI with ``${OPENAI_API_KEY}``, PostgreSQL with
    ``${DATABASE_URL}``, and JWT authentication.

    Returns:
        A StackConfig pre-configured for cloud deployment.
    """
    return StackConfig(
        name="remote",
        description="Cloud deployment stack with OpenAI, PostgreSQL, and JWT auth",
        llm={
            "default": LLMStackEntry(
                provider="openai",
                model="gpt-4o",
                temperature=0.1,
                max_tokens=8192,
                api_key="${OPENAI_API_KEY}",
                base_url="",
                timeout=None,
                max_retries=None,
            ),
            "fast": LLMStackEntry(
                provider="openai",
                model="gpt-4o-mini",
                temperature=0.0,
                max_tokens=8192,
                api_key="${OPENAI_API_KEY}",
                base_url="",
                timeout=None,
                max_retries=None,
            ),
            "judge": LLMStackEntry(
                provider="openai",
                model="gpt-4o",
                temperature=0.0,
                max_tokens=8192,
                api_key="${OPENAI_API_KEY}",
                base_url="",
                timeout=None,
                max_retries=None,
            ),
        },
        embedding=EmbeddingStackEntry(
            provider="openai",
            model="text-embedding-3-small",
            dimension=1536,
        ),
        database=DatabaseStackEntry(
            url="${DATABASE_URL}",
            pool_size=10,
            max_overflow=20,
        ),
        features=FeaturesStackEntry(
            enable_streaming=True,
            enable_a2a=True,
            enable_metrics=True,
            enable_rate_limit=True,
            enable_auth=True,
            enable_db=True,
        ),
        auth=AuthStackConfig(
            method="jwt",
            api_key="",
            jwks_url="${JWKS_URL}",
            issuer="${JWT_ISSUER}",
            audience="${JWT_AUDIENCE}",
        ),
    )


def get_default_stack_yaml(stack_name: str) -> str:
    """Return the YAML string representation of a built-in stack.

    Args:
        stack_name: The name of the built-in stack (``"local"`` or ``"remote"``).

    Returns:
        A YAML-formatted string for writing to disk.

    Raises:
        ValueError: If the stack name is not a recognised built-in.
    """
    if stack_name not in BUILTIN_STACKS:
        raise ValueError(
            f"Unknown built-in stack '{stack_name}'. Available: {', '.join(BUILTIN_STACKS)}"
        )
    stack = BUILTIN_STACKS[stack_name]()
    data = stack.model_dump(mode="json")
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    header = _STACK_HEADERS.get(stack_name, "")
    return f"{header}{body}"


BUILTIN_STACKS: dict[str, Callable[[], StackConfig]] = {
    "local": get_default_local_stack,
    "remote": get_default_remote_stack,
}

#: Comment blocks prepended to a generated stack file.
_STACK_HEADERS: dict[str, str] = {"local": _LOCAL_STACK_HEADER}
