"""Comprehensive end-to-end tests for all auto-generated agent API endpoints.

Tests every endpoint generated by ``create_default_router``:
  POST  /invoke                      sync invocation
  POST  /invoke/stream               SSE streaming
  POST  /chat                        session-aware chat
  GET   /health                      per-agent health
  GET   /config                      agent configuration
  GET   /prompts                     prompt versions
  GET   /card                        A2A agent card
  POST  /a2a/tasks                   A2A task submission
  GET   /a2a/tasks/{id}              A2A task status
  POST  /a2a/tasks/{id}/cancel       cancel A2A task
  POST  /threads                     create thread
  GET   /threads                     list threads
  GET   /threads/{id}                get thread
  PATCH /threads/{id}                update thread
  DELETE /threads/{id}               delete thread
  GET   /threads/{id}/messages       get messages
  DELETE /threads/{id}/messages      clear messages
  GET   /threads/{id}/summary        thread summary
  POST  /optimize/invoke             optimization invocation
  POST  /feedback                    submit feedback
  GET   /feedback                    list feedback
  GET   /feedback/export             export feedback as JSONL

Also covers:
  - Both functional agents (node_fn/graph_fn) and class agents (BaseGraphAgent)
  - Error cases: 404 for missing agent, 500 for agent failure, 422 for bad input
  - SSE protocol: chunked data frames, [DONE] sentinel, error frames
  - Chat with thread_id and history
  - A2A: synchronous fallback (no task manager) and async (with task manager)
  - Thread CRUD full lifecycle
  - Platform-level: /health, /readiness, /agents, /.well-known/agent.json
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

import pytest
from fastapi.testclient import TestClient

from agentomatic import AgentManifest, AgentPlatform
from agentomatic.agents import BaseGraphAgent
from agentomatic.storage.memory import MemoryStore

# ===========================================================================
# Test agents
# ===========================================================================


@dataclass
class _EchoState:
    request: str = ""
    output: dict[str, Any] = field(default_factory=dict)


class _ClassEchoAgent(BaseGraphAgent[_EchoState]):
    """BaseGraphAgent subclass — exercises the dataclass-state path."""

    agent_name = "class_echo"
    agent_description = "Class-based echo agent"
    agent_framework = "graph_agent"

    def build_graph(self) -> Any:
        g = self.new_graph()
        g.add_node("respond", self.respond)
        g.set_entry_point("respond")
        g.set_finish_point("respond")
        return g.compile()

    def respond(self, state: _EchoState) -> _EchoState:
        state.output = {
            "response": f"Class:{state.request}",
            "agent_type": "class-echo",
            "steps_taken": ["respond"],
        }
        return state

    def input_to_state(self, d: dict[str, Any]) -> _EchoState:
        return _EchoState(request=d.get("current_query", d.get("query", "")))

    def state_to_output(self, state: _EchoState) -> dict[str, Any]:
        return state.output


async def _echo_fn(state: dict[str, Any]) -> dict[str, Any]:
    """Functional agent: echoes query."""
    return {
        "response": f"Fn:{state.get('current_query', '')}",
        "agent_type": "fn-echo",
        "suggestions": ["try again"],
        "steps_taken": ["echo"],
        "citations": [{"source": "test"}],
        "metadata": {"fn": True},
    }


async def _fail_fn(state: dict[str, Any]) -> dict[str, Any]:
    raise RuntimeError("intended failure")


# ===========================================================================
# Platform fixtures
# ===========================================================================


def _build_platform(store: MemoryStore | None = None) -> AgentPlatform:
    p = AgentPlatform(
        agents_dir="/tmp/agentomatic_ep_test",
        title="EP Test",
        version="0.0.1",
        store=store,
        enable_studio=True,
    )
    # Functional echo agent
    p.register_agent(
        manifest=AgentManifest(
            name="echo",
            slug="fn-echo",
            description="Functional echo agent",
            version="1.0.0",
            intent_keywords=["echo"],
        ),
        node_fn=_echo_fn,
    )
    # Failing agent
    p.register_agent(
        manifest=AgentManifest(name="failer", slug="fn-failer", description="Always fails"),
        node_fn=_fail_fn,
    )
    # Class agent
    reg = _ClassEchoAgent().as_registered_agent()
    p.register_agent(
        manifest=reg.manifest,
        node_fn=reg.node_fn,
        graph_fn=reg.graph_fn,
        class_instance=reg.class_instance,
    )
    return p


@pytest.fixture
def store() -> MemoryStore:
    return MemoryStore()


@pytest.fixture
def client(store) -> Any:
    p = _build_platform(store=store)
    with TestClient(p.build()) as c:
        yield c


@pytest.fixture
def client_no_store() -> Any:
    p = _build_platform(store=None)
    with TestClient(p.build()) as c:
        yield c


# ===========================================================================
# Helpers
# ===========================================================================

BASE = "/api/v1"


def _invoke(client, name: str, query: str = "hello", **extra) -> Any:
    return client.post(f"{BASE}/{name}/invoke", json={"query": query, **extra})


def _stream_lines(client, name: str, query: str = "hello") -> list[str]:
    """Parse SSE stream into a list of data lines (stripped)."""
    resp = client.post(f"{BASE}/{name}/invoke/stream", json={"query": query})
    assert resp.status_code == 200, resp.text
    return [
        line[len("data: ") :].strip()
        for line in resp.text.splitlines()
        if line.startswith("data: ")
    ]


# ===========================================================================
# 1. Platform-level endpoints
# ===========================================================================


class TestPlatformEndpoints:
    def test_root_200(self, client):
        r = client.get("/")
        assert r.status_code == 200

    def test_docs_200(self, client):
        r = client.get("/docs")
        assert r.status_code == 200

    def test_openapi_json(self, client):
        r = client.get("/openapi.json")
        assert r.status_code == 200
        assert "paths" in r.json()

    def test_health_aggregated(self, client):
        r = client.get("/health")
        assert r.status_code == 200
        data = r.json()
        assert "status" in data or "agents" in data

    def test_readiness(self, client):
        r = client.get("/readiness")
        assert r.status_code in (200, 404)  # 404 if endpoint not mounted

    def test_agents_listing(self, client):
        r = client.get(f"{BASE}/agents")
        assert r.status_code == 200
        body = r.json()
        # Response shape: {"agents": {"<name>": {...}, ...}}
        agents_section = body.get("agents", body) if isinstance(body, dict) else {}
        if isinstance(agents_section, dict):
            # Keyed by agent name
            all_names = list(agents_section.keys())
        else:
            # List of agent dicts
            all_names = [a.get("name", a.get("slug", "")) for a in agents_section]
        assert any("echo" in n for n in all_names)

    def test_well_known_agent_json(self, client):
        r = client.get("/.well-known/agent.json")
        assert r.status_code == 200


# ===========================================================================
# 2. POST /invoke — sync
# ===========================================================================


class TestInvokeSync:
    def test_functional_agent_returns_200(self, client):
        r = _invoke(client, "echo", "world")
        assert r.status_code == 200
        data = r.json()
        assert data["response"] == "Fn:world"
        assert data["agent_type"] == "fn-echo"

    def test_response_fields_present(self, client):
        r = _invoke(client, "echo")
        data = r.json()
        for fname in ("response", "agent_type", "duration_ms", "metadata"):
            assert fname in data, f"missing field: {fname}"

    def test_duration_ms_positive(self, client):
        r = _invoke(client, "echo")
        assert r.json()["duration_ms"] >= 0.0

    def test_empty_query_still_200(self, client):
        r = _invoke(client, "echo", "")
        assert r.status_code == 200

    def test_missing_agent_404(self, client):
        r = _invoke(client, "does_not_exist")
        assert r.status_code == 404

    def test_failing_agent_500(self, client):
        r = _invoke(client, "failer")
        assert r.status_code == 500

    def test_class_agent_invoke(self, client):
        r = _invoke(client, "class_echo", "ping")
        assert r.status_code == 200
        assert r.json()["response"] == "Class:ping"

    def test_extra_fields_passed_through(self, client):
        r = client.post(
            f"{BASE}/echo/invoke",
            json={
                "query": "hi",
                "user_id": "tester",
                "prompt_version": "v1",
            },
        )
        assert r.status_code == 200

    def test_query_alias_current_query(self, client):
        """Class agents receive current_query through input_to_state."""
        # The HTTP schema always expects 'query'; the class agent's input_to_state
        # maps it to 'current_query' internally.
        r = client.post(f"{BASE}/class_echo/invoke", json={"query": "via_cq"})
        assert r.status_code == 200
        assert "via_cq" in r.json()["response"]


# ===========================================================================
# 3. POST /invoke/stream — SSE
# ===========================================================================


class TestInvokeStream:
    def test_status_200(self, client):
        r = client.post(f"{BASE}/echo/invoke/stream", json={"query": "stream"})
        assert r.status_code == 200

    def test_content_type_event_stream(self, client):
        r = client.post(f"{BASE}/echo/invoke/stream", json={"query": "ct"})
        assert "text/event-stream" in r.headers.get("content-type", "")

    def test_done_sentinel_present(self, client):
        lines = _stream_lines(client, "echo")
        assert "[DONE]" in lines

    def test_response_data_frame_present(self, client):
        lines = _stream_lines(client, "echo", "hello")
        # At least one data frame is not [DONE]
        frames = [ln for ln in lines if ln != "[DONE]"]
        assert len(frames) >= 1

    def test_response_payload_parseable(self, client):
        lines = _stream_lines(client, "echo", "parseable")
        frames = [ln for ln in lines if ln and ln != "[DONE]"]
        assert len(frames) >= 1
        first = json.loads(frames[0])
        assert isinstance(first, dict)
        assert "response" in first

    def test_class_agent_stream(self, client):
        lines = _stream_lines(client, "class_echo", "streamed")
        assert "[DONE]" in lines
        frames = [ln for ln in lines if ln and ln != "[DONE]"]
        # Class agents may emit per-node frames before the final payload.
        payloads = [json.loads(ln) for ln in frames]
        finals = [p for p in payloads if isinstance(p, dict) and "response" in p]
        assert finals
        assert finals[-1]["response"] == "Class:streamed"

    def test_failing_agent_stream_returns_error_frame(self, client):
        r = client.post(f"{BASE}/failer/invoke/stream", json={"query": "fail"})
        assert r.status_code == 200
        lines = _stream_lines(client, "failer", "fail")
        # Must emit an error frame (not a 500)
        error_frames = [ln for ln in lines if "error" in ln.lower()]
        assert len(error_frames) >= 1

    def test_x_agent_header(self, client):
        r = client.post(f"{BASE}/echo/invoke/stream", json={"query": "hdr"})
        assert r.headers.get("x-agent") == "echo"

    def test_missing_agent_stream_returns_done_or_error(self, client):
        r = client.post(f"{BASE}/ghost/invoke/stream", json={"query": "q"})
        # Either a 404 or an error SSE frame — both acceptable
        assert r.status_code in (200, 404)


# ===========================================================================
# 4. POST /chat
# ===========================================================================


class TestChat:
    def test_basic_chat_200(self, client):
        r = client.post(f"{BASE}/echo/chat", json={"content": "hello chat"})
        assert r.status_code == 200
        data = r.json()
        assert "response" in data
        assert "Fn:hello chat" in data["response"]

    def test_chat_response_fields(self, client):
        r = client.post(f"{BASE}/echo/chat", json={"content": "hi"})
        data = r.json()
        for f in ("response", "thread_id", "duration_ms"):
            assert f in data, f"missing field {f}"

    def test_chat_with_explicit_thread_id(self, client):
        r = client.post(
            f"{BASE}/echo/chat",
            json={
                "content": "msg",
                "thread_id": "thread-abc",
            },
        )
        assert r.status_code == 200
        assert r.json()["thread_id"] == "thread-abc"

    def test_chat_with_store_creates_thread(self, client):
        r = client.post(
            f"{BASE}/echo/chat",
            json={
                "content": "first message",
                "thread_id": "test-thread-1",
                "persist": True,
                "include_history": True,
            },
        )
        assert r.status_code == 200

    def test_class_agent_chat(self, client):
        r = client.post(f"{BASE}/class_echo/chat", json={"content": "class chat"})
        assert r.status_code == 200
        assert "Class:class chat" in r.json()["response"]

    def test_chat_failing_agent_500(self, client):
        r = client.post(f"{BASE}/failer/chat", json={"content": "crash"})
        assert r.status_code == 500

    def test_chat_missing_agent_404(self, client):
        r = client.post(f"{BASE}/ghost/chat", json={"content": "q"})
        assert r.status_code == 404

    def test_chat_without_store(self, client_no_store):
        r = client_no_store.post(f"{BASE}/echo/chat", json={"content": "no store"})
        assert r.status_code == 200

    def test_chat_with_user_supplied_messages(self, client):
        r = client.post(
            f"{BASE}/echo/chat",
            json={
                "content": "current message",
                "messages": [
                    {"role": "user", "content": "previous"},
                    {"role": "assistant", "content": "reply"},
                ],
            },
        )
        assert r.status_code == 200


# ===========================================================================
# 5. GET /health
# ===========================================================================


class TestAgentHealth:
    def test_echo_health_200(self, client):
        r = client.get(f"{BASE}/echo/health")
        assert r.status_code == 200
        data = r.json()
        assert "status" in data

    def test_class_echo_health_200(self, client):
        r = client.get(f"{BASE}/class_echo/health")
        assert r.status_code == 200

    def test_missing_agent_health_404(self, client):
        r = client.get(f"{BASE}/ghost/health")
        assert r.status_code == 404


# ===========================================================================
# 6. GET /config
# ===========================================================================


class TestAgentConfig:
    def test_config_returns_agent_name(self, client):
        r = client.get(f"{BASE}/echo/config")
        assert r.status_code == 200
        data = r.json()
        assert data["agent"] == "echo"

    def test_config_has_config_key(self, client):
        r = client.get(f"{BASE}/echo/config")
        assert "config" in r.json()

    def test_class_agent_config(self, client):
        r = client.get(f"{BASE}/class_echo/config")
        assert r.status_code == 200


# ===========================================================================
# 7. GET /prompts
# ===========================================================================


class TestAgentPrompts:
    def test_prompts_returns_versions(self, client):
        r = client.get(f"{BASE}/echo/prompts")
        assert r.status_code == 200
        data = r.json()
        assert "versions" in data
        assert "active" in data
        assert data["agent"] == "echo"

    def test_class_agent_prompts(self, client):
        r = client.get(f"{BASE}/class_echo/prompts")
        assert r.status_code == 200


# ===========================================================================
# 8. GET /card
# ===========================================================================


class TestAgentCard:
    def test_card_200(self, client):
        r = client.get(f"{BASE}/echo/card")
        assert r.status_code == 200

    def test_card_fields(self, client):
        data = client.get(f"{BASE}/echo/card").json()
        assert "name" in data
        assert "capabilities" in data
        assert "endpoints" in data

    def test_card_capabilities_streaming(self, client):
        caps = client.get(f"{BASE}/echo/card").json()["capabilities"]
        assert caps.get("streaming") is True
        assert caps.get("invoke") is True
        assert caps.get("chat") is True

    def test_card_endpoints_contain_invoke(self, client):
        eps = client.get(f"{BASE}/echo/card").json()["endpoints"]
        assert "invoke" in eps
        assert "echo/invoke" in eps["invoke"]

    def test_class_agent_card(self, client):
        r = client.get(f"{BASE}/class_echo/card")
        assert r.status_code == 200


# ===========================================================================
# 9. POST /a2a/tasks — A2A task lifecycle
# ===========================================================================


class TestA2ATasks:
    def _submit(self, client, content="A2A query", name="echo") -> dict:
        r = client.post(
            f"{BASE}/{name}/a2a/tasks",
            json={
                "message": {"content": content},
                "metadata": {},
            },
        )
        assert r.status_code == 200, r.text
        return r.json()

    def test_submit_returns_task_id(self, client):
        data = self._submit(client)
        assert "task_id" in data

    def test_submit_returns_status(self, client):
        data = self._submit(client)
        assert "status" in data

    def test_synchronous_fallback_has_result(self, client):
        """Without a task manager, A2A runs synchronously and result is inline."""
        data = self._submit(client)
        # Sync fallback: task completed inline
        if data.get("status") in ("completed", "succeeded"):
            assert "result" in data or "artifacts" in data

    def test_get_task_status(self, client):
        data = self._submit(client)
        task_id = data["task_id"]
        r = client.get(f"{BASE}/echo/a2a/tasks/{task_id}")
        # Either 200 (task store) or 404 (no task store, sync mode)
        assert r.status_code in (200, 404)

    def test_cancel_task(self, client):
        data = self._submit(client)
        task_id = data["task_id"]
        r = client.post(f"{BASE}/echo/a2a/tasks/{task_id}/cancel")
        assert r.status_code in (200, 404, 409)  # 409 if already completed

    def test_unknown_task_404(self, client):
        r = client.get(f"{BASE}/echo/a2a/tasks/nonexistent-id-12345")
        assert r.status_code == 404

    def test_class_agent_a2a(self, client):
        data = self._submit(client, name="class_echo", content="a2a class")
        assert "task_id" in data


# ===========================================================================
# 10. Thread endpoints
# ===========================================================================


class TestThreads:
    def test_list_threads_empty(self, client):
        r = client.get(f"{BASE}/echo/threads")
        assert r.status_code == 200
        data = r.json()
        assert "threads" in data or isinstance(data, list)

    def test_create_thread(self, client):
        r = client.post(
            f"{BASE}/echo/threads",
            json={
                "user_id": "user1",
                "title": "Test Thread",
            },
        )
        assert r.status_code == 200
        data = r.json()
        assert "thread_id" in data or "id" in data

    def test_get_thread(self, client):
        # Create first
        cr = client.post(f"{BASE}/echo/threads", json={"user_id": "u", "title": "T"})
        assert cr.status_code == 200
        tid = cr.json().get("thread_id") or cr.json().get("id", "")
        if tid:
            r = client.get(f"{BASE}/echo/threads/{tid}")
            assert r.status_code == 200

    def test_update_thread(self, client):
        cr = client.post(f"{BASE}/echo/threads", json={"user_id": "u", "title": "Old"})
        assert cr.status_code == 200
        tid = cr.json().get("thread_id") or cr.json().get("id", "")
        if tid:
            r = client.patch(f"{BASE}/echo/threads/{tid}", json={"title": "New"})
            assert r.status_code == 200

    def test_get_messages_empty(self, client):
        cr = client.post(f"{BASE}/echo/threads", json={"user_id": "u", "title": "T"})
        tid = cr.json().get("thread_id") or cr.json().get("id", "")
        if tid:
            r = client.get(f"{BASE}/echo/threads/{tid}/messages")
            assert r.status_code == 200
            data = r.json()
            assert "messages" in data or isinstance(data, list)

    def test_delete_thread(self, client):
        cr = client.post(f"{BASE}/echo/threads", json={"user_id": "u", "title": "Del"})
        tid = cr.json().get("thread_id") or cr.json().get("id", "")
        if tid:
            r = client.delete(f"{BASE}/echo/threads/{tid}")
            assert r.status_code == 200

    def test_clear_thread_messages(self, client):
        cr = client.post(f"{BASE}/echo/threads", json={"user_id": "u", "title": "Clr"})
        tid = cr.json().get("thread_id") or cr.json().get("id", "")
        if tid:
            r = client.delete(f"{BASE}/echo/threads/{tid}/messages")
            assert r.status_code == 200

    def test_thread_summary(self, client):
        cr = client.post(f"{BASE}/echo/threads", json={"user_id": "u", "title": "Sum"})
        tid = cr.json().get("thread_id") or cr.json().get("id", "")
        if tid:
            r = client.get(f"{BASE}/echo/threads/{tid}/summary")
            assert r.status_code == 200

    def test_get_nonexistent_thread_404(self, client):
        r = client.get(f"{BASE}/echo/threads/no-such-thread-id-xyz")
        assert r.status_code == 404

    def test_threads_no_store_returns_503_or_empty(self, client_no_store):
        r = client_no_store.get(f"{BASE}/echo/threads")
        assert r.status_code in (200, 503)

    def test_thread_list_with_user_filter(self, client):
        r = client.get(f"{BASE}/echo/threads?user_id=filterme")
        assert r.status_code == 200

    def test_full_thread_lifecycle(self, client):
        """Create → chat (persist) → get messages → clear → delete."""
        # 1. Chat to produce a turn
        chat_r = client.post(
            f"{BASE}/echo/chat",
            json={
                "content": "lifecycle test",
                "thread_id": "lifecycle-001",
                "persist": True,
            },
        )
        assert chat_r.status_code == 200

        # 2. Get messages
        msgs_r = client.get(f"{BASE}/echo/threads/lifecycle-001/messages")
        assert msgs_r.status_code == 200

        # 3. Clear messages
        clear_r = client.delete(f"{BASE}/echo/threads/lifecycle-001/messages")
        assert clear_r.status_code == 200

        # 4. Delete thread
        del_r = client.delete(f"{BASE}/echo/threads/lifecycle-001")
        assert del_r.status_code == 200


# ===========================================================================
# 11. POST /optimize/invoke
# ===========================================================================


class TestOptimizeInvoke:
    def test_optimize_invoke_200(self, client):
        r = client.post(
            f"{BASE}/echo/optimize/invoke",
            json={
                "query": "optimize me",
                "user_id": "optimizer",
                "include_retrieval_context": True,
                "include_steps": True,
            },
        )
        assert r.status_code == 200

    def test_optimize_invoke_response_fields(self, client):
        r = client.post(f"{BASE}/echo/optimize/invoke", json={"query": "q"})
        assert r.status_code == 200
        data = r.json()
        assert "response" in data
        assert "retrieval_context" in data
        assert "steps_taken" in data

    def test_optimize_invoke_with_prompt_override(self, client):
        r = client.post(
            f"{BASE}/echo/optimize/invoke",
            json={
                "query": "q",
                "system_prompt_override": "new system prompt",
            },
        )
        assert r.status_code == 200

    def test_class_agent_optimize_invoke(self, client):
        r = client.post(
            f"{BASE}/class_echo/optimize/invoke",
            json={
                "query": "class optimize",
            },
        )
        assert r.status_code == 200
        assert "response" in r.json()


# ===========================================================================
# 12. POST /feedback + GET /feedback + GET /feedback/export
# ===========================================================================


class TestFeedback:
    def test_submit_feedback_200(self, client):
        r = client.post(
            f"{BASE}/echo/feedback",
            json={
                "query": "what is agentomatic?",
                "response": "It is a platform.",
                "rating": 5,
                "user_id": "test-user",
            },
        )
        assert r.status_code == 200

    def test_submit_thumbs_up(self, client):
        r = client.post(
            f"{BASE}/echo/feedback",
            json={
                "query": "q",
                "response": "r",
                "rating": 1,
            },
        )
        assert r.status_code == 200

    def test_submit_thumbs_down_with_correction(self, client):
        # rating must be 1-5 (ge=1, le=5) per FeedbackRequest schema
        r = client.post(
            f"{BASE}/echo/feedback",
            json={
                "query": "q",
                "response": "r",
                "rating": 1,
                "correction": "The correct answer is X",
                "comment": "Response was wrong",
                "feedback_type": "correction",
            },
        )
        assert r.status_code == 200

    def test_list_feedback_200(self, client):
        # Submit one first
        client.post(f"{BASE}/echo/feedback", json={"query": "q", "response": "r", "rating": 1})
        r = client.get(f"{BASE}/echo/feedback")
        assert r.status_code == 200

    def test_export_feedback_200(self, client):
        r = client.get(f"{BASE}/echo/feedback/export")
        assert r.status_code == 200

    def test_class_agent_feedback(self, client):
        r = client.post(
            f"{BASE}/class_echo/feedback",
            json={
                "query": "q",
                "response": "r",
                "rating": 5,
            },
        )
        assert r.status_code == 200


# ===========================================================================
# 13. Studio endpoints
# ===========================================================================


class TestStudioEndpoints:
    def test_studio_run_stream_functional(self, client):
        """Studio stream for a node_fn agent: 200 + [DONE] sentinel.

        Studio is designed for graph agents (graph_fn); node_fn agents
        emit a run_error event in the stream but the HTTP status is still
        200 and the stream closes cleanly with [DONE].
        """
        r = client.post("/studio/agents/echo/runs/stream", json={"query": "studio"})
        assert r.status_code in (200, 404)
        if r.status_code == 200:
            # Stream must close cleanly — [DONE] must appear
            assert "[DONE]" in r.text

    def test_studio_run_stream_class_agent(self, client):
        r = client.post("/studio/agents/class_echo/runs/stream", json={"query": "studio class"})
        assert r.status_code in (200, 404)
        if r.status_code == 200:
            assert "run_error" not in r.text

    def test_studio_graph_endpoint(self, client):
        r = client.get("/studio/agents/class_echo/graph")
        assert r.status_code in (200, 404)


# ===========================================================================
# 14. Error contract
# ===========================================================================


class TestErrorContracts:
    def test_invoke_missing_agent_404_detail(self, client):
        r = client.post(f"{BASE}/nobody/invoke", json={"query": "q"})
        assert r.status_code == 404
        assert "detail" in r.json()

    def test_invoke_failure_returns_500(self, client):
        r = _invoke(client, "failer")
        assert r.status_code == 500

    def test_stream_missing_agent_handled(self, client):
        # Should either 404 or return error SSE — must not raise 500 internally
        r = client.post(f"{BASE}/nobody/invoke/stream", json={"query": "q"})
        assert r.status_code in (200, 404)

    def test_a2a_unknown_task(self, client):
        r = client.get(f"{BASE}/echo/a2a/tasks/aaaabbbbcccc")
        assert r.status_code == 404

    def test_chat_with_non_json_body(self, client):
        r = client.post(
            f"{BASE}/echo/chat",
            content="not-json",
            headers={"content-type": "application/json"},
        )
        assert r.status_code == 422


# ===========================================================================
# 15. Programmatic registration + multi-agent isolation
# ===========================================================================


class TestProgrammaticRegistration:
    def test_register_two_agents_isolated(self):
        p = AgentPlatform(agents_dir="/tmp/_ep_iso", enable_studio=False)

        async def agent_a(state):
            return {"response": "A"}

        async def agent_b(state):
            return {"response": "B"}

        p.register_agent(manifest=AgentManifest(name="agent_a", slug="agent-a"), node_fn=agent_a)
        p.register_agent(manifest=AgentManifest(name="agent_b", slug="agent-b"), node_fn=agent_b)
        app = p.build()

        with TestClient(app) as c:
            ra = c.post(f"{BASE}/agent_a/invoke", json={"query": "?"})
            rb = c.post(f"{BASE}/agent_b/invoke", json={"query": "?"})
            assert ra.json()["response"] == "A"
            assert rb.json()["response"] == "B"

    def test_custom_prefix(self):
        p = AgentPlatform(
            agents_dir="/tmp/_ep_pfx",
            enable_studio=False,
            api_prefix="/custom/v2",
        )

        async def fn(state):
            return {"response": "custom"}

        p.register_agent(manifest=AgentManifest(name="myagent", slug="myagent-slug"), node_fn=fn)
        app = p.build()
        with TestClient(app) as c:
            r = c.post("/custom/v2/myagent/invoke", json={"query": "q"})
            assert r.status_code == 200
            assert r.json()["response"] == "custom"


# ===========================================================================
# 16. Response shape contract (canonical AgentInvokeResponse)
# ===========================================================================


class TestResponseShape:
    CANONICAL_FIELDS = {
        "response",
        "agent_type",
        "duration_ms",
        "metadata",
        "suggestions",
        "citations",
        "steps_taken",
    }

    def test_invoke_canonical_fields(self, client):
        data = _invoke(client, "echo").json()
        for f in self.CANONICAL_FIELDS:
            assert f in data, f"missing canonical field: {f}"

    def test_suggestions_is_list(self, client):
        data = _invoke(client, "echo").json()
        assert isinstance(data["suggestions"], list)

    def test_citations_is_list(self, client):
        data = _invoke(client, "echo").json()
        assert isinstance(data["citations"], list)

    def test_steps_taken_is_list(self, client):
        data = _invoke(client, "echo").json()
        assert isinstance(data["steps_taken"], list)

    def test_metadata_is_dict(self, client):
        data = _invoke(client, "echo").json()
        assert isinstance(data["metadata"], dict)

    def test_class_agent_canonical_fields(self, client):
        data = _invoke(client, "class_echo", "fields").json()
        assert "response" in data


# ===========================================================================
# 17. Lifecycle hooks
# ===========================================================================


class TestLifecycleHooks:
    def test_before_after_node_hooks_called(self):
        p = AgentPlatform(agents_dir="/tmp/_hooks", enable_studio=False)
        before_calls: list[str] = []
        after_calls: list[str] = []

        async def fn(state):
            return {"response": "hooked"}

        p.register_agent(
            manifest=AgentManifest(name="hooked_agent", slug="hooked-agent"),
            node_fn=fn,
        )
        # Use the correct hook registration methods
        p.register_before_node_hook(lambda name, state: before_calls.append(name))
        p.register_after_node_hook(lambda name, result: after_calls.append(name))
        app = p.build()

        with TestClient(app) as c:
            c.post(f"{BASE}/hooked_agent/invoke", json={"query": "hook"})

        assert "hooked_agent" in before_calls
        assert "hooked_agent" in after_calls
