"""Deployment recommendation engine for the PromptFitter.

After fitting, the optimizer doesn't just produce "a better prompt".
It produces a **deployment recommendation** — canary rollout weights,
A/B routing, rollback triggers, and monitoring advice.

This is Agentomatic's deployment-first philosophy: optimisation outputs
are deployment artifacts, not compiled programs.

Classes
-------
- **DeploymentRecommendation** — rollout strategy with safety gates
- **RolloutConfig** — canary/A-B weights and thresholds
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from loguru import logger


@dataclass(slots=True)
class RolloutConfig:
    """Canary / A-B rollout configuration.

    Example::

        rollout = RolloutConfig(
            strategy="canary",
            initial_weight=0.20,
            promotion_threshold=0.05,
            rollback_threshold=-0.03,
            monitoring_hours=24,
        )
    """

    strategy: str = "canary"  # "canary", "blue_green", "shadow", "immediate"
    initial_weight: float = 0.20  # % of traffic to new version
    promotion_threshold: float = 0.05  # min improvement to auto-promote
    rollback_threshold: float = -0.03  # regression that triggers rollback
    monitoring_hours: int = 24  # hours to monitor before promotion
    max_error_rate: float = 0.05  # max error rate before rollback

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "strategy": self.strategy,
            "initial_weight": self.initial_weight,
            "promotion_threshold": self.promotion_threshold,
            "rollback_threshold": self.rollback_threshold,
            "monitoring_hours": self.monitoring_hours,
            "max_error_rate": self.max_error_rate,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RolloutConfig:
        """Deserialize from dictionary."""
        return cls(
            strategy=data.get("strategy", "canary"),
            initial_weight=data.get("initial_weight", 0.20),
            promotion_threshold=data.get("promotion_threshold", 0.05),
            rollback_threshold=data.get("rollback_threshold", -0.03),
            monitoring_hours=data.get("monitoring_hours", 24),
            max_error_rate=data.get("max_error_rate", 0.05),
        )


@dataclass(slots=True)
class DeploymentRecommendation:
    """Post-fit deployment recommendation.

    Generated by ``PromptFitter`` after ``fit()`` completes.  Contains
    everything needed to safely roll out the optimised configuration.

    Example::

        rec = DeploymentRecommendation(
            prompt_version="v2_optimized",
            confidence="high",
            rollout=RolloutConfig(strategy="canary", initial_weight=0.2),
            model_params={"temperature": 0.2, "top_p": 0.9},
            rag_params={"top_k": 6, "rerank": True},
            tool_policy={"force_tool_before_answer": True},
            monitoring_metrics=["faithfulness", "format_compliance", "p95_latency"],
            rollback_instructions="If faithfulness drops below 0.5, rollback to v1.",
        )

    Serialises to deployment-ready JSON::

        {
          "prompt_version": "v2_optimized",
          "model_params": {"temperature": 0.2, "top_p": 0.9},
          "rag_params": {"top_k": 6, "rerank": true},
          "tool_policy": {"force_tool_before_answer": true},
          "deployment_recommendation": {
            "rollout": "canary",
            "weight": 0.2
          }
        }
    """

    # ── Version info ──────────────────────────────────────────────
    prompt_version: str = "v2_optimized"
    confidence: str = "medium"  # "high", "medium", "low"

    # ── Rollout strategy ──────────────────────────────────────────
    rollout: RolloutConfig = field(default_factory=RolloutConfig)

    # ── Optimised parameters ──────────────────────────────────────
    model_params: dict[str, Any] = field(default_factory=dict)
    rag_params: dict[str, Any] = field(default_factory=dict)
    tool_policy: dict[str, Any] = field(default_factory=dict)

    # ── Monitoring ────────────────────────────────────────────────
    monitoring_metrics: list[str] = field(default_factory=list)
    rollback_instructions: str = ""
    safety_notes: list[str] = field(default_factory=list)

    # ── Model routing ─────────────────────────────────────────────
    recommended_model: str | None = None
    fallback_model: str | None = None
    routing_weights: dict[str, float] = field(default_factory=dict)

    # ── Metrics ───────────────────────────────────────────────────
    expected_improvement: float = 0.0
    baseline_score: float = 0.0
    projected_score: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        """Serialize to deployment-ready dictionary."""
        d: dict[str, Any] = {
            "prompt_version": self.prompt_version,
            "confidence": self.confidence,
        }

        if self.model_params:
            d["model_params"] = self.model_params
        if self.rag_params:
            d["rag_params"] = self.rag_params
        if self.tool_policy:
            d["tool_policy"] = self.tool_policy

        d["deployment_recommendation"] = {
            "rollout": self.rollout.strategy,
            "weight": self.rollout.initial_weight,
            "monitoring_hours": self.rollout.monitoring_hours,
        }

        if self.recommended_model:
            d["model_routing"] = {
                "primary": self.recommended_model,
                "fallback": self.fallback_model,
            }
            if self.routing_weights:
                d["model_routing"]["weights"] = self.routing_weights

        if self.monitoring_metrics:
            d["monitoring"] = {
                "metrics": self.monitoring_metrics,
                "rollback_threshold": self.rollout.rollback_threshold,
            }
            if self.rollback_instructions:
                d["monitoring"]["rollback_instructions"] = self.rollback_instructions

        if self.safety_notes:
            d["safety_notes"] = self.safety_notes

        d["expected_improvement"] = round(self.expected_improvement, 4)
        d["baseline_score"] = round(self.baseline_score, 4)
        d["projected_score"] = round(self.projected_score, 4)

        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DeploymentRecommendation:
        """Deserialize from dictionary."""
        rollout_data = data.get("deployment_recommendation", {})
        routing_data = data.get("model_routing", {})
        monitoring_data = data.get("monitoring", {})

        return cls(
            prompt_version=data.get("prompt_version", "v2_optimized"),
            confidence=data.get("confidence", "medium"),
            rollout=RolloutConfig(
                strategy=rollout_data.get("rollout", "canary"),
                initial_weight=rollout_data.get("weight", 0.20),
                monitoring_hours=rollout_data.get("monitoring_hours", 24),
            ),
            model_params=data.get("model_params", {}),
            rag_params=data.get("rag_params", {}),
            tool_policy=data.get("tool_policy", {}),
            monitoring_metrics=monitoring_data.get("metrics", []),
            rollback_instructions=monitoring_data.get("rollback_instructions", ""),
            safety_notes=data.get("safety_notes", []),
            recommended_model=routing_data.get("primary"),
            fallback_model=routing_data.get("fallback"),
            routing_weights=routing_data.get("weights", {}),
            expected_improvement=data.get("expected_improvement", 0.0),
            baseline_score=data.get("baseline_score", 0.0),
            projected_score=data.get("projected_score", 0.0),
        )

    def summary(self) -> str:
        """Human-readable deployment summary."""
        lines = [
            "",
            "━" * 60,
            "🚀 DEPLOYMENT RECOMMENDATION",
            "━" * 60,
            f"  Version:     {self.prompt_version}",
            f"  Confidence:  {self.confidence}",
            f"  Strategy:    {self.rollout.strategy} ({self.rollout.initial_weight:.0%} traffic)",
            f"  Monitor for: {self.rollout.monitoring_hours}h",
            "",
            f"  Baseline:    {self.baseline_score:.4f}",
            f"  Projected:   {self.projected_score:.4f}",
            f"  Expected Δ:  {self.expected_improvement:+.4f}",
        ]

        if self.model_params:
            lines.append(f"  Model params: {self.model_params}")
        if self.rag_params:
            lines.append(f"  RAG params:   {self.rag_params}")
        if self.tool_policy:
            lines.append(f"  Tool policy:  {self.tool_policy}")
        if self.recommended_model:
            lines.append(f"  Model:        {self.recommended_model}")
            if self.fallback_model:
                lines.append(f"  Fallback:     {self.fallback_model}")

        if self.safety_notes:
            lines.append("")
            lines.append("  ⚠️ Safety notes:")
            for note in self.safety_notes:
                lines.append(f"    - {note}")

        if self.rollback_instructions:
            lines.append("")
            lines.append(f"  🔄 Rollback: {self.rollback_instructions}")

        lines.append("━" * 60)
        return "\n".join(lines)


def build_deployment_recommendation(
    fit_result: Any,  # PromptFitResult
    version: str = "v2_optimized",
    rollout_strategy: str = "canary",
    initial_weight: float = 0.20,
) -> DeploymentRecommendation:
    """Build a ``DeploymentRecommendation`` from a ``PromptFitResult``.

    Automatically determines confidence level, safety notes, monitoring
    metrics, and rollback instructions based on the fit results.

    Args:
        fit_result: The result from ``PromptFitter.fit()``.
        version: Prompt version label for the deployment.
        rollout_strategy: Rollout strategy (canary, blue_green, immediate).
        initial_weight: Initial traffic weight for canary rollout.

    Returns:
        A populated ``DeploymentRecommendation``.
    """
    improvement = fit_result.absolute_improvement

    # ── Confidence level ──────────────────────────────────────────
    if improvement >= 0.10:
        confidence = "high"
    elif improvement >= 0.05:
        confidence = "medium"
    elif improvement > 0:
        confidence = "low"
    else:
        confidence = "no_improvement"

    # ── Rollout config ────────────────────────────────────────────
    if confidence == "high":
        weight = min(initial_weight * 2, 0.50)
        monitoring_hours = 12
    elif confidence == "low":
        weight = min(initial_weight * 0.5, 0.10)
        monitoring_hours = 48
    elif confidence == "no_improvement":
        weight = 0.0
        monitoring_hours = 0
        rollout_strategy = "hold"
    else:
        weight = initial_weight
        monitoring_hours = 24

    rollout = RolloutConfig(
        strategy=rollout_strategy,
        initial_weight=weight,
        monitoring_hours=monitoring_hours,
    )

    # ── Monitoring metrics ────────────────────────────────────────
    monitoring_metrics = list(fit_result.metric_deltas.keys())
    if not monitoring_metrics:
        monitoring_metrics = ["composite_score"]

    # ── Safety notes ──────────────────────────────────────────────
    safety_notes: list[str] = []

    # Check for regressions
    for dim, delta in fit_result.metric_deltas.items():
        if delta < -0.02:
            safety_notes.append(
                f"⚠️ Regression detected in '{dim}': {delta:+.4f}. "
                f"Monitor closely during rollout."
            )

    if confidence == "low":
        safety_notes.append(
            "Small improvement margin. Consider running additional eval rounds."
        )

    # ── Rollback instructions ─────────────────────────────────────
    worst_dim = min(fit_result.metric_deltas.items(), key=lambda x: x[1], default=("composite", 0.0))
    rollback_instructions = (
        f"If '{worst_dim[0]}' drops below baseline, "
        f"rollback to {fit_result.baseline_config.system_prompt[:30]}... (previous version)."
    )

    return DeploymentRecommendation(
        prompt_version=version,
        confidence=confidence,
        rollout=rollout,
        model_params=fit_result.best_config.model_params,
        rag_params=fit_result.best_config.rag_params,
        tool_policy=fit_result.best_config.tool_params,
        monitoring_metrics=monitoring_metrics,
        rollback_instructions=rollback_instructions,
        safety_notes=safety_notes,
        expected_improvement=improvement,
        baseline_score=fit_result.baseline_score,
        projected_score=fit_result.best_score,
    )
