"""LLM and embedding provider abstractions."""

from __future__ import annotations

from .auth_token import (
    AsyncTokenProvider,
    OAuth2ClientCredentialsTokenProvider,
    StaticTokenProvider,
    TokenProvider,
    TokenResponseError,
)
from .embeddings import (
    HashEmbedder,
    get_embeddings,
    register_embedding_provider,
    registered_embedding_providers,
    reset_embeddings,
)
from .fallback import (
    DEFAULT_FALLBACK_ON,
    EmptyLLMResponseError,
    FallbackLLM,
    is_empty_llm_response,
    model_label,
    normalize_fallback_on,
    should_fallback,
)
from .jsonutil import (
    extract_json,
    extract_json_array,
    extract_json_object,
    loads_repaired,
    repair_json,
)
from .llm import (
    StructuredOutputFallbackWrapper,
    apply_stack_defaults,
    astream_with_thinking,
    get_failover_count,
    get_llm,
    get_llm_for_agent,
    get_named_llm,
    get_structured_llm,
    invoke_with_retry,
    record_failover,
    register_llm_provider,
    registered_llm_providers,
    reset_llm,
    set_llm,
    unregister_llm_provider,
)
from .message_utils import (
    SplitMessage,
    attach_thinking_metadata,
    llm_result_metadata,
    message_text,
    message_thinking,
    split_llm_message,
    split_thinking_text,
    strip_thinking_for_json,
)
from .retry import DEFAULT_RETRYABLE_EXCEPTIONS, RetryConfig, async_retry_call, retry_call

__all__ = [
    "DEFAULT_FALLBACK_ON",
    "DEFAULT_RETRYABLE_EXCEPTIONS",
    "AsyncTokenProvider",
    "EmptyLLMResponseError",
    "FallbackLLM",
    "HashEmbedder",
    "OAuth2ClientCredentialsTokenProvider",
    "RetryConfig",
    "SplitMessage",
    "StaticTokenProvider",
    "StructuredOutputFallbackWrapper",
    "TokenProvider",
    "TokenResponseError",
    "apply_stack_defaults",
    "astream_with_thinking",
    "async_retry_call",
    "attach_thinking_metadata",
    "extract_json",
    "extract_json_array",
    "extract_json_object",
    "get_embeddings",
    "get_failover_count",
    "get_llm",
    "get_llm_for_agent",
    "get_named_llm",
    "get_structured_llm",
    "invoke_with_retry",
    "is_empty_llm_response",
    "llm_result_metadata",
    "loads_repaired",
    "message_text",
    "message_thinking",
    "model_label",
    "normalize_fallback_on",
    "record_failover",
    "register_embedding_provider",
    "register_llm_provider",
    "registered_embedding_providers",
    "registered_llm_providers",
    "repair_json",
    "reset_embeddings",
    "reset_llm",
    "retry_call",
    "set_llm",
    "should_fallback",
    "split_llm_message",
    "split_thinking_text",
    "strip_thinking_for_json",
    "unregister_llm_provider",
]
