"""Control plane REST API.

A production-oriented admin surface for observing and operating the
platform at runtime: inspect agents / endpoints / connections, drain or
re-enable individual agents, toggle maintenance mode, and read a sanitised
configuration snapshot.

Mutating operations can be protected by a shared ``control_token`` supplied
via the ``X-Control-Token`` header.
"""

from __future__ import annotations

import hmac
from typing import TYPE_CHECKING, Any

from fastapi import APIRouter, Header, HTTPException
from loguru import logger

from agentomatic.control.models import (
    ControlAgentInfo,
    ControlConnectionInfo,
    ControlConnectionProbe,
    ControlEndpointInfo,
    ControlInfo,
    ControlMetricsSummary,
    MaintenanceRequest,
    ToggleResponse,
)
from agentomatic.control.state import ControlPlaneState
from agentomatic.core.errors import client_safe_message

if TYPE_CHECKING:
    from agentomatic.core.platform import AgentPlatform


def create_control_router(
    platform: AgentPlatform,
    state: ControlPlaneState,
    *,
    control_token: str = "",
) -> APIRouter:
    """Create the control plane router.

    Args:
        platform: The owning :class:`AgentPlatform` (read for live state).
        state: Shared :class:`ControlPlaneState`.
        control_token: Optional shared secret; when set, mutating endpoints
            require a matching ``X-Control-Token`` header.

    Returns:
        A configured :class:`~fastapi.APIRouter`.
    """
    router = APIRouter(tags=["Control Plane"])

    def _authorize(token: str | None) -> None:
        """Reject mutating requests lacking the configured control token."""
        # Bytes comparison — see the note in agentomatic.middleware.auth: a
        # non-ASCII token would otherwise raise TypeError and surface as 500.
        if control_token and (
            not token or not hmac.compare_digest(token.encode(), control_token.encode())
        ):
            raise HTTPException(status_code=401, detail="Invalid or missing control token")

    def _agent_aliases(agent: Any) -> set[str]:
        """Return every path segment an agent's routes are mounted under.

        Agents are mounted under both their folder name and their manifest
        slug when the two differ (see ``_mount_agent_router`` in
        ``core/platform.py``) — both must be tracked so enable/disable
        can't be bypassed via whichever alias wasn't targeted.
        """
        manifest = getattr(agent, "manifest", None)
        aliases = {getattr(manifest, "name", None), getattr(manifest, "slug", None)}
        return {alias for alias in aliases if alias}

    def _agent_policy(agent: Any) -> tuple[bool, list[str], list[str]]:
        """Extract (requires_auth, roles, scopes) from an agent policy."""
        policy = getattr(agent, "security_policy", None)
        if policy is None:
            return False, [], []
        return (
            bool(getattr(policy, "require_auth", False)),
            list(getattr(policy, "allowed_roles", []) or []),
            list(getattr(policy, "allowed_scopes", []) or []),
        )

    def _connection_names(agent: Any) -> list[str]:
        """Return the connection names declared by an agent."""
        configs = getattr(agent, "connections", None) or []
        return [getattr(c, "name", "?") for c in configs]

    def _public_connection_health(result: Any) -> dict[str, Any]:
        """Return the strictly allow-listed connection diagnostics for clients.

        Driver and custom connection health checks are extension points, so
        their dictionaries must be treated as untrusted operational data.  In
        particular, a URL/DSN, headers, provider metadata, or a raw exception
        can contain credentials.  Keep the control-plane payload useful for
        operators without making it a configuration-exfiltration endpoint.
        """
        health = result if isinstance(result, dict) else {}
        allowed = ("connection", "kind", "status", "purpose", "backend", "provider")
        public = {key: health[key] for key in allowed if health.get(key) is not None}
        public["status"] = str(public.get("status", "unknown"))

        # ``detail`` is generated by ConnectionManager solely for an unset
        # ${ENV} target; third-party health checks cannot surface arbitrary
        # detail strings through this public API.
        if public["status"] == "not_configured" and health.get("detail"):
            public["detail"] = str(health["detail"])
        if health.get("error"):
            public["error"] = client_safe_message(
                Exception(str(health["error"])), context="connection health check failed"
            )
        return public

    async def _storage_health() -> dict[str, Any] | None:
        """Expose the platform persistence backend as a probeable connection.

        The platform's durable store is configured separately from the
        agent-scoped connection registry.  Treating it as a platform resource
        keeps it visible to operators without pretending it belongs to an
        agent, and lets Studio exercise the exact same live health check used
        by deployment readiness checks.
        """
        store = platform.store
        if store is None:
            return None
        try:
            health = await store.health_check()
        except Exception as exc:  # noqa: BLE001
            health = {
                "status": "error",
                "error": client_safe_message(exc, context="storage health check failed"),
            }
        if not isinstance(health, dict):
            health = {"status": "healthy"}
        # Store implementations may include driver exceptions or a URL in
        # their own result.  The SQLAlchemy store intentionally redacts
        # credentials; errors are redacted here before a public control read.
        result = _public_connection_health(
            {
                **health,
                "connection": "storage",
                "kind": "database",
                "purpose": "persistence",
            }
        )
        return result

    async def _connections_by_scope() -> list[ControlConnectionInfo]:
        """Collect managed connections plus the platform's durable storage."""
        from agentomatic.connections.manager import PLATFORM_SCOPE, all_managers

        out = []
        for scope, manager in all_managers().items():
            health = await manager.health_check()
            public_health = {
                name: _public_connection_health(result) for name, result in health.items()
            }
            out.append(ControlConnectionInfo(scope=scope, connections=public_health))
        storage = await _storage_health()
        if storage is None:
            return out
        platform_scope = next((item for item in out if item.scope == PLATFORM_SCOPE), None)
        if platform_scope is None:
            # Keep platform resources first, matching the longstanding
            # ordering when a platform connection manager is present.
            out.insert(
                0, ControlConnectionInfo(scope=PLATFORM_SCOPE, connections={"storage": storage})
            )
        else:
            platform_scope.connections["storage"] = storage
        return out

    # -- introspection ---------------------------------------------------

    @router.get("", response_model=ControlInfo, summary="Platform overview")
    async def control_info() -> ControlInfo:
        """Return a high-level snapshot of the platform."""
        from agentomatic.connections.manager import all_managers

        return ControlInfo(
            platform=platform.title,
            version=platform.version,
            uptime_seconds=state.uptime_seconds,
            maintenance_mode=state.maintenance_mode,
            agent_count=platform._registry.count,
            endpoint_count=platform.endpoint_registry.count,
            plugin_count=platform._plugin_registry.count,
            pipeline_count=len(platform.pipelines),
            connection_scopes=len(all_managers()),
            control_token_required=bool(control_token),
        )

    async def _agent_health(agent: Any, *, timeout: float = 2.0) -> dict[str, Any]:
        """Run agent health_check with a hard timeout so control APIs stay snappy."""
        import asyncio

        try:
            result = await asyncio.wait_for(agent.health_check(), timeout=timeout)
            return result if isinstance(result, dict) else {"status": "healthy"}
        except TimeoutError:
            return {"status": "timeout", "error": "health_check timed out"}
        except Exception as exc:  # noqa: BLE001
            # These control *reads* are not token-gated, so never echo raw
            # exception text from a backend health check.
            return {
                "status": "error",
                "error": client_safe_message(exc, context="health_check failed"),
            }

    def _public_agent_health(result: Any) -> dict[str, Any]:
        """Return the small, safe health contract exposed by control reads.

        Agent health checks are application extension points.  Their raw
        output can therefore contain exception text, provider responses, or
        arbitrary configuration values.  The control plane is intentionally
        an operator surface rather than a mechanism for exporting that data;
        retain only standard readiness signals and a sanitised error.
        """
        health = result if isinstance(result, dict) else {}
        public: dict[str, Any] = {"status": str(health.get("status", "unknown"))}
        for key in ("node_fn_ready", "graph_ready", "has_config"):
            if isinstance(health.get(key), bool):
                public[key] = health[key]
        if health.get("error"):
            public["error"] = client_safe_message(
                Exception(str(health["error"])), context="health_check failed"
            )
        return public

    @router.get("/agents", response_model=list[ControlAgentInfo], summary="List agents")
    async def list_agents() -> list[ControlAgentInfo]:
        """List all agents with operational metadata."""
        infos: list[ControlAgentInfo] = []
        for name, agent in platform._registry.all().items():
            requires_auth, roles, scopes = _agent_policy(agent)
            health = _public_agent_health(await _agent_health(agent))
            infos.append(
                ControlAgentInfo(
                    name=name,
                    slug=agent.slug,
                    description=agent.manifest.description,
                    version=agent.manifest.version,
                    framework=agent.manifest.framework,
                    enabled=not state.is_agent_disabled(name),
                    requires_auth=requires_auth,
                    allowed_roles=roles,
                    allowed_scopes=scopes,
                    connections=_connection_names(agent),
                    health=health,
                )
            )
        return infos

    @router.get(
        "/agents/{name}",
        response_model=ControlAgentInfo,
        summary="Get agent detail",
    )
    async def get_agent(name: str) -> ControlAgentInfo:
        """Return operational detail for a single agent."""
        agent = platform._registry.get(name)
        if agent is None:
            raise HTTPException(404, f"Agent '{name}' not found")
        requires_auth, roles, scopes = _agent_policy(agent)
        health = _public_agent_health(await _agent_health(agent))
        return ControlAgentInfo(
            name=name,
            slug=agent.slug,
            description=agent.manifest.description,
            version=agent.manifest.version,
            framework=agent.manifest.framework,
            enabled=not state.is_agent_disabled(name),
            requires_auth=requires_auth,
            allowed_roles=roles,
            allowed_scopes=scopes,
            connections=_connection_names(agent),
            health=health,
        )

    @router.get(
        "/endpoints",
        response_model=list[ControlEndpointInfo],
        summary="List custom endpoints",
    )
    async def list_endpoints() -> list[ControlEndpointInfo]:
        """List all registered custom endpoints."""
        infos: list[ControlEndpointInfo] = []
        for ep in platform.endpoint_registry.list_endpoints().values():
            data = ep.info()
            infos.append(ControlEndpointInfo(**data))
        return infos

    @router.get(
        "/connections",
        response_model=list[ControlConnectionInfo],
        summary="Connection health by scope",
    )
    async def list_connections() -> list[ControlConnectionInfo]:
        """Report connection and durable-storage health for every scope."""
        return await _connections_by_scope()

    @router.get(
        "/connections/{scope}/{name}",
        response_model=ControlConnectionProbe,
        summary="Probe a single connection",
    )
    async def probe_connection(scope: str, name: str) -> ControlConnectionProbe:
        """Run the live health probe for one database, vector or service connection."""
        from agentomatic.connections.manager import PLATFORM_SCOPE, all_managers

        if scope == PLATFORM_SCOPE and name == "storage":
            storage = await _storage_health()
            if storage is None:
                raise HTTPException(404, "Platform storage is not configured")
            return ControlConnectionProbe.model_validate(storage)

        manager = all_managers().get(scope)
        if manager is None:
            raise HTTPException(404, f"Connection scope '{scope}' not found")
        try:
            result = await manager.health_check_connection(name)
        except KeyError:
            raise HTTPException(404, f"Connection '{name}' not found in scope '{scope}'") from None
        return ControlConnectionProbe.model_validate(_public_connection_health(result))

    @router.get("/health", summary="Aggregate platform health")
    async def control_health() -> dict[str, Any]:
        """Aggregate health across agents, endpoints and connections."""
        from agentomatic.connections.manager import all_managers

        agents: dict[str, Any] = {}
        for name, agent in platform._registry.all().items():
            agents[name] = _public_agent_health(await _agent_health(agent))

        connections: dict[str, Any] = {}
        for scope, manager in all_managers().items():
            health = await manager.health_check()
            connections[scope] = {
                name: _public_connection_health(result) for name, result in health.items()
            }
        storage = await _storage_health()
        if storage is not None:
            from agentomatic.connections.manager import PLATFORM_SCOPE

            connections.setdefault(PLATFORM_SCOPE, {})["storage"] = storage

        overall = (
            "healthy" if all(a.get("status") == "healthy" for a in agents.values()) else "degraded"
        )
        return {
            "status": "maintenance" if state.maintenance_mode else overall,
            "uptime_seconds": state.uptime_seconds,
            "agents": agents,
            "endpoints": [
                e.endpoint_name for e in platform.endpoint_registry.list_endpoints().values()
            ],
            "connections": connections,
        }

    @router.get(
        "/metrics/summary",
        response_model=ControlMetricsSummary,
        summary="Coarse operational counters",
    )
    async def metrics_summary() -> ControlMetricsSummary:
        """Return coarse counters for dashboards / quick checks."""
        from agentomatic.connections.manager import all_managers

        try:
            from agentomatic.observability.metrics import HAS_PROMETHEUS
        except Exception:  # noqa: BLE001
            HAS_PROMETHEUS = False

        return ControlMetricsSummary(
            agents=platform._registry.count,
            disabled_agents=len(state.disabled_agents),
            endpoints=platform.endpoint_registry.count,
            plugins=platform._plugin_registry.count,
            pipelines=len(platform.pipelines),
            connection_scopes=len(all_managers()),
            prometheus_available=bool(HAS_PROMETHEUS),
        )

    @router.get("/config", summary="Sanitised configuration snapshot")
    async def control_config() -> dict[str, Any]:
        """Return a sanitised view of the effective platform configuration."""
        return {
            "title": platform.title,
            "version": platform.version,
            "api_prefix": platform.api_prefix,
            "agents_dir": str(platform.agents_dir),
            "features": {
                "auth": platform._enable_auth,
                "jwt_auth": platform._enable_jwt_auth,
                "zero_trust": platform._enable_zero_trust,
                "rate_limit": platform._enable_rate_limit,
                "metrics": platform._enable_metrics,
                "telemetry": platform._enable_telemetry,
                "studio": platform._enable_studio,
            },
        }

    # -- operations (mutating) ------------------------------------------

    @router.post(
        "/agents/{name}/disable",
        response_model=ToggleResponse,
        summary="Disable (drain) an agent",
    )
    async def disable_agent(
        name: str,
        x_control_token: str | None = Header(default=None),
    ) -> ToggleResponse:
        """Stop routing traffic to an agent (returns 503 for its routes)."""
        _authorize(x_control_token)
        agent = platform._registry.get(name)
        if agent is None:
            raise HTTPException(404, f"Agent '{name}' not found")
        # An agent is mounted under BOTH its folder name and its manifest
        # slug when they differ (so Studio, which addresses agents by slug,
        # doesn't 404). Disable both aliases, or draining by whichever one
        # the operator didn't use leaves the other alias's routes live.
        for alias in _agent_aliases(agent):
            state.disable_agent(alias)
        logger.warning(f"🛑 Control plane: agent '{name}' disabled")
        return ToggleResponse(target=name, state="disabled")

    @router.post(
        "/agents/{name}/enable",
        response_model=ToggleResponse,
        summary="Re-enable an agent",
    )
    async def enable_agent(
        name: str,
        x_control_token: str | None = Header(default=None),
    ) -> ToggleResponse:
        """Resume routing traffic to a previously disabled agent."""
        _authorize(x_control_token)
        agent = platform._registry.get(name)
        if agent is None:
            raise HTTPException(404, f"Agent '{name}' not found")
        for alias in _agent_aliases(agent):
            state.enable_agent(alias)
        logger.info(f"✅ Control plane: agent '{name}' enabled")
        return ToggleResponse(target=name, state="enabled")

    @router.post(
        "/maintenance",
        response_model=ToggleResponse,
        summary="Toggle maintenance mode",
    )
    async def set_maintenance(
        request: MaintenanceRequest,
        x_control_token: str | None = Header(default=None),
    ) -> ToggleResponse:
        """Enable or disable platform-wide maintenance mode."""
        _authorize(x_control_token)
        state.maintenance_mode = request.enabled
        logger.warning(f"🔧 Control plane: maintenance_mode={request.enabled}")
        return ToggleResponse(
            target="platform",
            state="maintenance" if request.enabled else "active",
        )

    return router
