"""Single source of truth for the Agentomatic *agent primer*.

The primer bootstraps any coding agent (Cursor, Claude, etc.) working inside an
Agentomatic project. It is emitted by ``agentomatic agents-guide`` — either to
stdout or written into a project as ``AGENTS.md``, ``CLAUDE.md``, or a Cursor
skill at ``.cursor/skills/agentomatic/SKILL.md``.

Keeping the content here (one module string) guarantees the CLI, docs, and the
in-repo agent knowledge files stay in sync.
"""

from __future__ import annotations

from pathlib import Path

from agentomatic._version import __version__

#: Relative paths that ``agents-guide --write`` knows how to target.
WRITE_TARGETS: tuple[str, ...] = (
    "AGENTS.md",
    "CLAUDE.md",
    ".cursor/skills/agentomatic/SKILL.md",
)

#: YAML front matter prepended when writing a Cursor skill file.
_SKILL_FRONTMATTER = """\
---
name: agentomatic
description: |-
  Build, optimize, and deploy multi-agent AI systems with the Agentomatic
  platform. Activate for agent creation, the scaffolded main.py, deploy
  profiles, Studio debugging, prompt/Keras-style optimization, or CLI usage.
---

"""

_PRIMER_BODY = f"""\
# Agentomatic — Agent Primer

> Generated by `agentomatic agents-guide` (agentomatic v{__version__}).
> Agentomatic is a **zero-boilerplate multi-agent API platform** on FastAPI: drop
> agents into folders and it auto-generates a production REST API, a Studio debug
> UI, prompt optimization, storage, auth, and observability.

## Install

```bash
pip install "agentomatic[all]"      # everything (recommended for projects)
pip install agentomatic             # core only
```

## The develop → optimize → deploy loop

```bash
# 1. Scaffold a project (main.py + agents/ plugins/ endpoints/ stacks/ ...)
agentomatic new my_platform && cd my_platform
agentomatic init hello --template basic     # add an agent under agents/

# 2. Develop: run everything locally (Studio at /studio/ui, docs at /docs)
#    Prefers uvicorn main:app when main.py is present (same as deploy).
agentomatic run                              # http://127.0.0.1:8000

# 3. Optimize (prompt tuning / Keras-style fit) against a dataset
agentomatic optimize hello --dataset data.jsonl

# 4. Deploy: generate a container that serves the SAME app via uvicorn
agentomatic deploy --stack remote --distroless          # full profile
agentomatic deploy --profile minimal --stack remote     # production-lean
```

## Key CLI commands

| Command | Purpose |
| --- | --- |
| `agentomatic new NAME` | Scaffold a full project (alias for `init --project`) |
| `agentomatic init NAME [--project] [--template basic\\|full\\|class\\|rag\\|chatbot\\|coordinator\\|extraction\\|deepagent\\|legacy_dict\\|ingestion]` | Scaffold an agent (or project) |
| `agentomatic add connection\\|ingestion NAME` | Add components to an existing agent |
| `agentomatic run [--studio/--no-studio] [--with-ui] [--port 8000] [--ssl-certfile ...] [--require-auth-globally]` | Start the platform (prefers `main:app` when present) |
| `agentomatic deploy [--profile full\\|minimal] [--minimal] [--distroless] [--stack NAME]` | Generate Dockerfile/compose/.env |
| `agentomatic demo` | Run a self-contained demo platform + Studio |
| `agentomatic list` / `inspect NAME` / `doctor` | Discover, inspect, diagnose |
| `agentomatic optimize AGENT --dataset data.jsonl` | Prompt / Keras-style optimization |
| `agentomatic test NAME` / `ui` | Interactive console / Chainlit chat UI |
| `agentomatic stack init\\|list\\|show\\|use\\|export` | Multi-environment stack management |
| `agentomatic pipeline list` | Discover YAML/Python pipelines |
| `agentomatic agents-guide [--write TARGET] [--force]` | Emit this primer into a project |

## Class-agent pattern (recommended)

Subclass `BaseGraphAgent` and implement `input_to_state` — the server converts the
incoming request dict into your dataclass state on **every** path (REST
`invoke`/`chat`/`invoke/stream`/`optimize`/A2A + Studio streaming). Never assume a
raw dict reaches your nodes.

```python
# agents/hello/agent.py
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from agentomatic.agents import BaseGraphAgent


@dataclass
class HelloState:
    request: str = ""
    output: dict[str, Any] = field(default_factory=dict)


class HelloAgent(BaseGraphAgent[HelloState]):
    agent_name = "hello"
    agent_description = "Greets the caller"
    agent_framework = "graph_agent"

    def build_graph(self) -> Any:
        g = self.new_graph()
        g.add_node("respond", self.respond)
        g.set_entry_point("respond")
        g.set_finish_point("respond")
        return g.compile()

    def respond(self, state: HelloState) -> HelloState:
        state.output = {{"response": f"Hello, {{state.request}}!"}}
        return state

    def input_to_state(self, data: dict[str, Any]) -> HelloState:
        return HelloState(request=data.get("current_query", ""))

    def state_to_output(self, state: HelloState) -> dict[str, Any]:
        return state.output
```

## Deployed container == `agentomatic run`

`agentomatic deploy` renders a Dockerfile that runs `uvicorn main:app`. Locally,
`agentomatic run` also prefers `main:app` when a project `main.py` is present
(so Metrics/JWT/startup hooks match deploy). The scaffolded `main.py` builds a
fully-featured, **env-driven** `app` — nothing is silently dropped.

Agents mount at **`/api/v1/{{agent_name}}/invoke`** (no `/agents/` segment).

### Deploy profiles

- **full** (default): everything on — REST API, Swagger, Studio UI, health,
  metrics, auth.
- **minimal** (`--profile minimal` / `--minimal`): production-lean — Studio UI off
  and quieter logs, but the REST API, health/readiness, metrics, and auth stay on.
- **Swagger is always available** in both profiles (`/docs`, `/redoc`,
  `/openapi.json` are never gated by the profile).

Both profiles use one code path: the profile just bakes `AGENTOMATIC_*` env vars
into the image/compose that drive the same `main.py`.

### Environment variables (drive `main.py` in dev and containers)

| Var | Effect |
| --- | --- |
| `AGENTOMATIC_ENABLE_STUDIO` | Studio UI on/off (default on; `0` in `--profile minimal`) |
| `AGENTOMATIC_ENABLE_METRICS` | Prometheus metrics (default on) |
| `AGENTOMATIC_LOG_LEVEL` | Log level (default `INFO`; `WARNING` in minimal) |
| `AGENTOMATIC_ENABLE_AUTH` / `AGENTOMATIC_API_KEY` | API-key auth |
| `AGENTOMATIC_ENABLE_JWT` | JWT auth (configure JWKS via stack) |
| `AGENTOMATIC_REQUIRE_AUTH` | Require auth globally (implies JWT + zero-trust) |
| `AGENTOMATIC_ENABLE_CONTROL_PLANE` / `AGENTOMATIC_CONTROL_TOKEN` | Control plane |
| `AGENTOMATIC_ENABLE_RATE_LIMIT` | Rate limiting |
| `AGENTOMATIC_TITLE` | Platform title |
| `AGENTOMATIC_STACK` | Active stack name |
| `AGENTOMATIC_AGENTS` | Comma-separated allow-list scoping agent discovery |

## Security defaults (safe by default)

- **`--require-auth-globally` refuses to boot** without real verification: you must
  configure JWKS (JWT signature verification) or API-key auth. Unsigned/forged JWTs
  are never accepted, and token expiry is always verified.
- **CORS wildcard hardening**: with `cors_origins=["*"]` the platform disables
  `allow_credentials` (and warns once). Set explicit `cors_origins=[...]` to enable
  credentialed CORS.

## Provider-agnostic principle (bring your own backend)

Agentomatic ships the ops (routing, storage interface, observability) but **no
first-party vendor connectors**. Register your own vector / embedding / store
providers with any SDK:

```python
from agentomatic import AgentPlatform

platform = AgentPlatform.from_folder("agents/")
platform.register_vector_provider("my_vec", my_factory)
platform.register_embedding_provider("my_emb", my_embed_factory)
platform.register_store_provider("my_store", my_store_factory)
```

Do **not** add first-party Cosmos (or other vendor) connectors to the framework.

### Custom DB & vector-store connections

Wire **any** custom client (async or sync SDK, graph/time-series DB, in-house
package) as a lifecycle-managed connection. Declare it in an agent's
`connections.py`; the platform builds one client per process (lazily) and closes
it on shutdown (`aclose`/`close`/`disconnect`).

```python
from agentomatic.connections import (
    VectorConnectionConfig, CustomConnectionConfig,
    register_vector_provider, register_vector_store_adapter,
    register_connection_type, get_connections, initialize_connections,
)

register_vector_provider("my_db", lambda cfg: MyAsyncClient(cfg.url, **cfg.options))
register_vector_store_adapter("my_db", MyDbStore)  # upsert/query/delete
# In a node: store = await get_connections(self.agent_name).vector("kb").as_store()
```

- Provider names are **not** limited to the built-ins — any registered name works
  (unknown names raise a clear error pointing at `register_vector_provider`).
- Sync-only SDKs: wrap blocking calls in `asyncio.to_thread` inside the adapter.
- Non-vector backends: `CustomConnectionConfig(factory="pkg.mod:make", args=[...])`.
- **Never build the client in `BaseGraphAgent.__init__`** — use the builder/factory.
- Standalone runs (bare `get_graph()`, scripts): call
  `await initialize_connections(scope, CONNECTIONS)` since there's no platform
  lifecycle. Full guide: `docs/guide/custom-connections.md`.

## Optimization & honest evaluation

- `agent.compile(...)` / `agent.fit(...)` / `agent.save/load(...)` provide a
  Keras-style optimization loop for class agents.
- Plugin `eval` computes a **real** metric (or fails clearly) — no fabricated
  scores. After `optimize()`, inspect `agent._last_optimize_status` (`"ok"` or
  `"skipped: <reason>"`).
- Model defaults resolve provider-agnostically from `AGENTOMATIC_TASK_MODEL` /
  `LLM__MODEL` before any local fallback.

## Project conventions (match these when editing the framework)

- `from __future__ import annotations` is the first import in every Python file.
- Google-style docstrings; line length 99; absolute imports from `agentomatic`.
- `TYPE_CHECKING` blocks for type-only imports.
- Tests: `pytest` + `pytest-asyncio` (auto). Use `SimpleNamespace(name=...)` (not
  `MagicMock(name=...)`) when a `.name` attribute is read.
- Run the gate: `uv run ruff check src/agentomatic/ tests/`,
  `uv run ruff format --check src/agentomatic/ tests/`,
  `uv run mypy src/agentomatic/ --ignore-missing-imports`,
  `uv run pytest tests/ -q --override-ini='addopts='`,
  `uv run mkdocs build --strict`.
- Conventional Commits (`feat`, `fix`, `docs`, ...); releases via Python Semantic
  Release.
"""


def render_primer(target: str | None = None) -> str:
    """Return the primer text, optionally framed for a specific target.

    Args:
        target: Optional write target (see :data:`WRITE_TARGETS`). When it is a
            Cursor skill file, YAML front matter is prepended so the file is a
            valid ``SKILL.md``.

    Returns:
        The primer markdown as a string.
    """
    if target is not None and target.endswith("SKILL.md"):
        return _SKILL_FRONTMATTER + _PRIMER_BODY
    return _PRIMER_BODY


def write_primer(target: str, *, root: Path | str = ".", force: bool = False) -> Path:
    """Write the primer into a project at *target*.

    Args:
        target: One of :data:`WRITE_TARGETS` (a project-relative path).
        root: Project root the target is resolved against.
        force: Overwrite an existing file when ``True``.

    Returns:
        The absolute path that was written.

    Raises:
        ValueError: If *target* is not a known write target.
        FileExistsError: If the file exists and *force* is ``False``.
    """
    if target not in WRITE_TARGETS:
        raise ValueError(f"unknown write target {target!r}; expected one of {WRITE_TARGETS}")
    dest = Path(root) / target
    if dest.exists() and not force:
        raise FileExistsError(f"{dest} already exists (use --force to overwrite)")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render_primer(target))
    return dest
