"""Deployment scaffolding for the ``agentomatic deploy`` CLI command.

Generates production-ready deployment artefacts (Dockerfile, docker-compose,
``.env.example``, and optional nginx configuration) tailored to the active
stack.  Files are written to a target directory (default
``deploy/generated/``) so operators can inspect, tweak, and commit them
before shipping.

The generated Dockerfile mirrors the reference multi-stage image at the
repository root (rootless ``USER appuser`` with ``uv``-managed venv) and
uses the ``agentomatic run`` entrypoint so the CLI and container behave
identically.  A ``--distroless`` variant is produced from
``gcr.io/distroless/python3-debian12`` which runs under the built-in
``nonroot`` user (numeric UID 65532) — verified to have execute
permissions on ``/app/.venv/bin/python``.

Example::

    agentomatic deploy --stack local --out deploy/generated
    agentomatic deploy --stack remote --distroless --agents-dir agents

Environment variable placeholders are derived from the active
:class:`~agentomatic.stacks.manager.StackConfig` so operators know which
secrets to populate at deployment time.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from agentomatic._version import __version__

if TYPE_CHECKING:
    from agentomatic.stacks.manager import LLMStackEntry, StackConfig


# Project artefacts copied into the image, in a stable order. Only those that
# actually exist in the project are emitted so ``docker build`` never fails on
# a missing COPY source.
_PROJECT_COPY_CANDIDATES: tuple[str, ...] = (
    "main.py",
    "agents",
    "plugins",
    "endpoints",
    "ingestion",
    "pipelines",
    "stacks",
    "requirements.txt",
)


def _copy_lines(project_root: Path | None, *, chown: str | None = None) -> list[str]:
    """Return ``COPY`` lines for the project artefacts that exist.

    Args:
        project_root: Directory to scan for known project files/dirs. When
            ``None`` (or nothing matches) a sensible default set is emitted so
            a standalone Dockerfile still references ``main.py`` + component
            folders.
        chown: Optional ``user:group`` (or numeric UID:GID) for ``--chown=``.

    Returns:
        A list of ``COPY`` instructions (context-relative paths).
    """
    own = f" --chown={chown}" if chown else ""

    def _line(candidate: str, *, is_dir: bool) -> str:
        if is_dir:
            return f"COPY{own} {candidate}/ ./{candidate}/"
        return f"COPY{own} {candidate} ./{candidate}"

    lines: list[str] = []
    if project_root is not None:
        for candidate in _PROJECT_COPY_CANDIDATES:
            path = project_root / candidate
            if path.exists():
                lines.append(_line(candidate, is_dir=path.is_dir()))
    if lines:
        return lines

    # Fallback: no scan or nothing found — emit the canonical project layout.
    default_dirs = ("agents", "plugins", "endpoints", "ingestion", "pipelines", "stacks")
    return [_line("main.py", is_dir=False)] + [_line(d, is_dir=True) for d in default_dirs]


# ---------------------------------------------------------------------------
# Deploy plan data model
# ---------------------------------------------------------------------------


@dataclass
class DeployPlan:
    """Result of a deploy generation run.

    Attributes:
        out_dir: Directory into which files were written.
        files: Mapping of relative path → absolute path for every file
            generated by the deploy command.
        stack_name: Name of the stack used for env derivation.
        distroless: Whether a distroless Dockerfile was produced.
    """

    out_dir: Path
    files: dict[str, Path] = field(default_factory=dict)
    stack_name: str = ""
    distroless: bool = False


# ---------------------------------------------------------------------------
# Rootless multi-stage Dockerfile (mirrors repo-root Dockerfile)
# ---------------------------------------------------------------------------


def render_dockerfile(
    *,
    version: str = __version__,
    project_root: Path | None = None,
) -> str:
    """Return a project-appropriate rootless multi-stage Dockerfile.

    Unlike the framework repo image, this installs ``agentomatic`` from PyPI
    (pinned to *version*) instead of assuming a ``pyproject.toml`` / ``src/``
    layout, then copies the user's project directories and launches their
    ``main.py`` via ``uvicorn main:app`` so the ``AgentPlatform`` config in
    ``main.py`` is honoured.

    Args:
        version: ``agentomatic`` version to pin (``agentomatic[all]==<version>``).
        project_root: Project directory to scan for artefacts to ``COPY``.
            When ``None`` a default layout is emitted.
    """
    copies = "\n".join(_copy_lines(project_root, chown="appuser:appuser"))
    return f"""\
# =============================================================================
# Agentomatic — Multi-stage Dockerfile (rootless)
# Generated by `agentomatic deploy` for an agentomatic *project* (main.py +
# agents/ plugins/ ...). Installs agentomatic from PyPI pinned to {version}.
# =============================================================================

# ---- Build stage ------------------------------------------------------------
FROM python:3.12-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Isolated virtualenv so we can copy just the deps into the runtime stage.
RUN python -m venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"

RUN pip install --upgrade pip \\
    && pip install "agentomatic[all]=={version}"

# ---- Runtime stage ----------------------------------------------------------
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PATH="/app/.venv/bin:$PATH" \\
    VIRTUAL_ENV="/app/.venv"

RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    ca-certificates \\
    && rm -rf /var/lib/apt/lists/* \\
    && apt-get autoremove -y \\
    && apt-get clean

# Non-root user for the runtime process (rootless container)
RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app

COPY --from=builder --chown=appuser:appuser /app/.venv /app/.venv
{copies}

RUN mkdir -p /app/logs /app/tmp /app/data \\
    && chown -R appuser:appuser /app

USER appuser

HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \\
    CMD curl -f http://localhost:8000/health || exit 1

EXPOSE 8000

# Launch the user's platform (main.py exposes ``app = platform.build()``) so
# the AgentPlatform config is honoured. Swap for ``agentomatic run`` only if
# you do not use main.py.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


# ---------------------------------------------------------------------------
# Distroless Dockerfile (rootless via built-in nonroot / uid 65532)
# ---------------------------------------------------------------------------


def render_dockerfile_distroless(
    *,
    version: str = __version__,
    project_root: Path | None = None,
) -> str:
    """Return a distroless project Dockerfile that runs as ``nonroot``.

    ``gcr.io/distroless/python3-debian12`` ships with a pre-created
    ``nonroot`` account at numeric UID ``65532``; we set that explicitly so
    image scanners and Kubernetes ``runAsNonRoot`` policies do not have to
    introspect the base image. ``agentomatic`` is installed from PyPI (pinned
    to *version*) in the build stage; distroless has no shell, so the app is
    launched by invoking ``uvicorn`` directly through the venv Python.

    Args:
        version: ``agentomatic`` version to pin (``agentomatic[all]==<version>``).
        project_root: Project directory to scan for artefacts to ``COPY``.
    """
    copies = "\n".join(_copy_lines(project_root, chown="65532:65532"))
    return f"""\
# =============================================================================
# Agentomatic — Distroless Dockerfile (rootless, minimal attack surface)
# Generated by `agentomatic deploy --distroless`. Installs agentomatic from
# PyPI pinned to {version} and launches the project's main.py.
# =============================================================================

# ---- Build stage ------------------------------------------------------------
FROM python:3.12-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python -m venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"

RUN pip install --upgrade pip \\
    && pip install "agentomatic[all]=={version}"

# Copy project sources into the build stage so they can be chowned + carried
# into the runtime stage (distroless cannot chown at runtime — no shell).
{copies}

# Ensure the runtime user (uid 65532) can read the venv and sources
RUN chown -R 65532:65532 /app

# ---- Runtime stage (distroless, non-root by default) ------------------------
FROM gcr.io/distroless/python3-debian12:nonroot

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PATH="/app/.venv/bin:$PATH" \\
    VIRTUAL_ENV="/app/.venv"

WORKDIR /app

COPY --from=builder --chown=65532:65532 /app /app

# Explicitly set numeric UID for Kubernetes runAsNonRoot admission
USER 65532:65532

EXPOSE 8000

# Distroless has no shell but can execute binaries directly. Launch uvicorn
# through the venv Python so main.py's AgentPlatform config is honoured.
ENTRYPOINT ["/app/.venv/bin/python", "-m", "uvicorn"]
CMD ["main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


# ---------------------------------------------------------------------------
# docker-compose.yml (platform + optional per-agent stubs)
# ---------------------------------------------------------------------------


def render_docker_compose(
    *,
    stack_name: str,
    agent_names: list[str] | None = None,
    dockerfile_name: str = "Dockerfile",
    env_file: str = ".env",
    build_context: str = ".",
    volume_prefix: str = ".",
) -> str:
    """Return a docker-compose file wiring the platform and optional agents.

    Args:
        stack_name: Human-friendly name of the active stack (for comments).
        agent_names: Optional list of agent names for which per-agent service
            stubs are emitted.  Each stub reuses the platform image but
            overrides ``AGENTOMATIC_AGENTS`` so operators can split traffic
            per agent behind a shared reverse proxy.
        dockerfile_name: Path to the Dockerfile *relative to* ``build_context``.
        env_file: Relative path to the ``.env`` file that Compose will load.
        build_context: Docker build context relative to the compose file
            (points back at the project root so ``COPY main.py`` etc. resolve).
        volume_prefix: Host-path prefix for bind mounts, relative to the
            compose file (matches ``build_context`` so mounts find the project).
    """
    stubs = ""
    for name in agent_names or []:
        service = name.replace("_", "-").lower()
        stubs += (
            f"\n  agent-{service}:\n"
            f"    build:\n"
            f"      context: {build_context}\n"
            f"      dockerfile: {dockerfile_name}\n"
            f"    image: agentomatic:latest\n"
            f"    container_name: agentomatic-{service}\n"
            f"    restart: unless-stopped\n"
            f"    env_file: {env_file}\n"
            f"    environment:\n"
            f"      - AGENTOMATIC_AGENTS={name}\n"
            f"    depends_on:\n"
            f"      - platform\n"
            f"    ports:\n"
            f'      - "0:8000"  # dynamic host port; use reverse proxy for routing\n'
        )

    return f"""\
# =============================================================================
# Agentomatic — docker-compose (stack: {stack_name})
# Generated by `agentomatic deploy`.  Adjust ports, volumes, and secrets
# before promoting to a shared environment.
# =============================================================================

services:
  platform:
    build:
      context: {build_context}
      dockerfile: {dockerfile_name}
    image: agentomatic:latest
    container_name: agentomatic-platform
    restart: unless-stopped
    env_file: {env_file}
    environment:
      - AGENTOMATIC_STACK={stack_name}
    ports:
      - "8000:8000"
    volumes:
      - {volume_prefix}/agents:/app/agents:ro
      - {volume_prefix}/plugins:/app/plugins:ro
      - {volume_prefix}/endpoints:/app/endpoints:ro
      - {volume_prefix}/ingestion:/app/ingestion:ro
      - {volume_prefix}/pipelines:/app/pipelines:ro
      - {volume_prefix}/stacks:/app/stacks:ro
      - agentomatic-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
{stubs}
volumes:
  agentomatic-data:
"""


# ---------------------------------------------------------------------------
# nginx reverse proxy (optional; documents HTTPS termination)
# ---------------------------------------------------------------------------


def render_nginx_conf() -> str:
    """Return a starter ``nginx.conf`` that terminates TLS in front of the app.

    The certificate paths reference the standard Let's Encrypt layout; users
    are expected to substitute their own certificates or plug this into a
    Caddy / Traefik deployment instead.
    """
    return """\
# =============================================================================
# Agentomatic — nginx reverse proxy with TLS termination
# Generated by `agentomatic deploy`.  Adjust server_name and cert paths.
# =============================================================================

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream agentomatic {
        server platform:8000;
    }

    # HTTP → HTTPS redirect
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    # HTTPS terminator
    server {
        listen 443 ssl http2;
        server_name agentomatic.example.com;

        ssl_certificate     /etc/letsencrypt/live/agentomatic/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/agentomatic/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # SSE / streaming responses require buffering off + long timeouts.
        proxy_buffering off;
        proxy_read_timeout 3600s;

        client_max_body_size 25m;

        location / {
            proxy_pass http://agentomatic;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
"""


# ---------------------------------------------------------------------------
# .env.example derivation from a StackConfig
# ---------------------------------------------------------------------------


def _llm_env_lines(profile: str, entry: LLMStackEntry) -> list[str]:
    """Return ``LLM__*`` env lines for a single LLM profile.

    The first / default profile writes canonical ``LLM__PROVIDER`` /
    ``LLM__MODEL`` keys; additional profiles are emitted as comments so
    operators know which knobs exist without polluting the runtime env.
    """
    is_default = profile == "default"
    prefix = "" if is_default else "# "
    lines = [
        f"{prefix}LLM__PROVIDER={entry.provider}",
        f"{prefix}LLM__MODEL={entry.model}",
        f"{prefix}LLM__TEMPERATURE={entry.temperature}",
        f"{prefix}LLM__MAX_TOKENS={entry.max_tokens}",
    ]
    if entry.base_url:
        if entry.provider == "ollama":
            lines.append(f"{prefix}LLM__OLLAMA_BASE_URL={entry.base_url}")
        else:
            lines.append(f"{prefix}LLM__BASE_URL={entry.base_url}")
    if entry.api_key:
        key_var = f"LLM__{entry.provider.upper()}_API_KEY"
        # Show placeholder as-is (usually ``${OPENAI_API_KEY}``) so the
        # operator knows which secret to inject at runtime.
        lines.append(f"{prefix}{key_var}={entry.api_key}")
    return lines


def render_env_example(stack: StackConfig) -> str:
    """Derive a ``.env.example`` from a resolved :class:`StackConfig`.

    Non-secret values are emitted directly; secrets that reference
    ``${ENV_VAR}`` in the stack are preserved verbatim so operators see
    which environment variables must exist at container start.  Extra
    (non-default) LLM profiles are emitted as comments to document
    alternative wirings.
    """
    lines: list[str] = [
        "# =============================================================",
        f"# Agentomatic — .env for stack '{stack.name}'",
        "# Generated by `agentomatic deploy`.",
        "# =============================================================",
        "",
        "# --- Application -------------------------------------------------",
        f'APP_NAME="Agentomatic ({stack.name})"',
        "APP_ENV=production",
        "LOG_LEVEL=INFO",
        f"AGENTOMATIC_STACK={stack.name}",
        "",
        "# --- LLM (default profile) --------------------------------------",
    ]

    default_entry = stack.llm.get("default")
    if default_entry is None and stack.llm:
        first_key = next(iter(stack.llm))
        default_entry = stack.llm[first_key]
    if default_entry is not None:
        lines.extend(_llm_env_lines("default", default_entry))

    extras = [k for k in stack.llm if k != "default"]
    if extras:
        lines += ["", "# --- LLM (additional profiles — commented) ----------------------"]
        for profile in extras:
            lines.append(f"# ~ profile: {profile}")
            lines.extend(_llm_env_lines(profile, stack.llm[profile]))

    lines += [
        "",
        "# --- Embedding ---------------------------------------------------",
        f"EMBEDDING__PROVIDER={stack.embedding.provider}",
        f"EMBEDDING__MODEL={stack.embedding.model}",
        f"EMBEDDING__DIMENSION={stack.embedding.dimension}",
        "",
        "# --- Database ----------------------------------------------------",
        f"DB__URL={stack.database.url}",
        f"DB__POOL_SIZE={stack.database.pool_size}",
        f"DB__MAX_OVERFLOW={stack.database.max_overflow}",
        "",
        "# --- Feature flags ----------------------------------------------",
        f"FEATURES__ENABLE_STREAMING={str(stack.features.enable_streaming).lower()}",
        f"FEATURES__ENABLE_A2A={str(stack.features.enable_a2a).lower()}",
        f"FEATURES__ENABLE_METRICS={str(stack.features.enable_metrics).lower()}",
        f"FEATURES__ENABLE_RATE_LIMIT={str(stack.features.enable_rate_limit).lower()}",
        f"FEATURES__ENABLE_AUTH={str(stack.features.enable_auth).lower()}",
        f"FEATURES__ENABLE_DB={str(stack.features.enable_db).lower()}",
        "",
        "# --- Authentication ---------------------------------------------",
        f"# AUTH__METHOD={stack.auth.method}",
    ]
    if stack.auth.api_key:
        lines.append(f"AUTH__API_KEY={stack.auth.api_key}")
    if stack.auth.jwks_url:
        lines.append(f"AUTH__JWKS_URL={stack.auth.jwks_url}")
    if stack.auth.issuer:
        lines.append(f"AUTH__ISSUER={stack.auth.issuer}")
    if stack.auth.audience:
        lines.append(f"AUTH__AUDIENCE={stack.auth.audience}")

    # Preserve any inline environment overrides declared on the stack —
    # these are usually secrets or additional integration knobs.
    if stack.environment:
        lines += ["", "# --- Inline environment overrides (from stack) ------------------"]
        for key, value in stack.environment.items():
            lines.append(f"{key}={value}")

    lines.append("")  # trailing newline
    return "\n".join(lines)


def render_env_example_default() -> str:
    """Return a minimal ``.env.example`` used when no stack is resolvable."""
    return """\
# =============================================================
# Agentomatic — .env (fallback, no stack resolved)
# Generated by `agentomatic deploy`.
# =============================================================
APP_NAME="Agentomatic"
APP_ENV=production
LOG_LEVEL=INFO

# --- LLM ---
LLM__PROVIDER=ollama
LLM__MODEL=mistral:7b
LLM__OLLAMA_BASE_URL=http://localhost:11434

# --- Database ---
DB__URL=sqlite+aiosqlite:///data/platform.db
"""


# ---------------------------------------------------------------------------
# Stack loading + agent discovery helpers
# ---------------------------------------------------------------------------


def load_stack(
    stack_name: str | None,
    *,
    stacks_dir: str | Path = "stacks",
) -> StackConfig | None:
    """Load a stack by name, falling back to built-ins when the file is absent.

    Args:
        stack_name: Explicit stack name; when ``None`` the active stack file
            (``.agentomatic-stack``) or the ``AGENTOMATIC_STACK`` env var is
            consulted, defaulting to ``"local"``.
        stacks_dir: Directory containing ``*.yaml`` stack files.

    Returns:
        The resolved :class:`StackConfig`, or ``None`` if loading fails
        (built-in defaults handle the common case).
    """
    import os

    from agentomatic.stacks.manager import StackManager

    if stack_name is None:
        stack_name = os.environ.get("AGENTOMATIC_STACK", "")
        if not stack_name:
            active_file = Path(".agentomatic-stack")
            if active_file.exists():
                stack_name = active_file.read_text().strip()
        if not stack_name:
            stack_name = "local"

    manager = StackManager(stacks_dir=stacks_dir)
    try:
        return manager.load(stack_name)
    except Exception:  # noqa: BLE001 — deploy must not crash on missing stacks
        return None


def discover_agent_names(agents_dir: str | Path) -> list[str]:
    """Return the names of agent packages living under ``agents_dir``.

    An "agent package" is a directory that contains either an
    ``__init__.py`` or an ``agent.py`` file — matching the discovery
    heuristic used by :meth:`AgentPlatform.build`.
    """
    root = Path(agents_dir)
    if not root.exists():
        return []
    names: list[str] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir() or entry.name.startswith(("_", ".")):
            continue
        if (entry / "__init__.py").exists() or (entry / "agent.py").exists():
            names.append(entry.name)
    return names


# ---------------------------------------------------------------------------
# Orchestration entry point
# ---------------------------------------------------------------------------


def generate_deploy(
    out_dir: str | Path,
    *,
    stack_name: str | None = None,
    stacks_dir: str | Path = "stacks",
    agents_dir: str | Path = "agents",
    distroless: bool = False,
    include_nginx: bool = True,
    include_agent_stubs: bool = False,
) -> DeployPlan:
    """Generate the full deploy artefact set under ``out_dir``.

    Args:
        out_dir: Target directory (created if missing).
        stack_name: Stack to derive env / compose metadata from.
        stacks_dir: Where to look for stack YAML files.
        agents_dir: Where to enumerate agents for optional per-agent
            compose stubs.
        distroless: When ``True`` emit ``Dockerfile.distroless`` and wire the
            compose service to build from it.
        include_nginx: Emit ``nginx.conf`` alongside a note in the compose
            file about terminating TLS via reverse proxy.
        include_agent_stubs: When ``True`` emit one compose service per
            discovered agent (useful for split-deployments).

    Returns:
        A :class:`DeployPlan` describing every file that was written.
    """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # The project root is the parent of the agents dir (``agents/`` lives at
    # the project root). Deploy artefacts usually live under
    # ``deploy/generated/``, so the build context / bind mounts must point
    # back at the project root relative to the compose file.
    project_root = Path(agents_dir).resolve().parent
    rel_context = os.path.relpath(project_root, out_path.resolve()).replace(os.sep, "/") or "."

    stack = load_stack(stack_name, stacks_dir=stacks_dir)
    resolved_name = stack.name if stack is not None else (stack_name or "local")

    plan = DeployPlan(out_dir=out_path, stack_name=resolved_name, distroless=distroless)

    dockerfile_name = "Dockerfile.distroless" if distroless else "Dockerfile"
    dockerfile_content = (
        render_dockerfile_distroless(version=__version__, project_root=project_root)
        if distroless
        else render_dockerfile(version=__version__, project_root=project_root)
    )
    dockerfile_path = out_path / dockerfile_name
    dockerfile_path.write_text(dockerfile_content)
    plan.files[dockerfile_name] = dockerfile_path

    # Dockerfile path expressed relative to the build context (project root).
    dockerfile_rel = os.path.relpath(dockerfile_path.resolve(), project_root).replace(os.sep, "/")

    agent_names = discover_agent_names(agents_dir) if include_agent_stubs else None
    compose_content = render_docker_compose(
        stack_name=resolved_name,
        agent_names=agent_names,
        dockerfile_name=dockerfile_rel,
        env_file=".env",
        build_context=rel_context,
        volume_prefix=rel_context,
    )
    compose_path = out_path / "docker-compose.yml"
    compose_path.write_text(compose_content)
    plan.files["docker-compose.yml"] = compose_path

    env_content = render_env_example(stack) if stack is not None else render_env_example_default()
    env_path = out_path / ".env.example"
    env_path.write_text(env_content)
    plan.files[".env.example"] = env_path

    if include_nginx:
        nginx_path = out_path / "nginx.conf"
        nginx_path.write_text(render_nginx_conf())
        plan.files["nginx.conf"] = nginx_path

    readme = _render_readme(plan)
    readme_path = out_path / "README.md"
    readme_path.write_text(readme)
    plan.files["README.md"] = readme_path

    return plan


def _render_readme(plan: DeployPlan) -> str:
    """Return the README that ships alongside the generated deploy files."""
    dockerfile = "Dockerfile.distroless" if plan.distroless else "Dockerfile"
    return f"""\
# Generated deploy artefacts

Stack: **{plan.stack_name}**  |  Base image: **{"distroless" if plan.distroless else "python:3.12-slim"}**

## Files

- `{dockerfile}` — rootless multi-stage build (runs as `appuser` /
  numeric UID 65532 for distroless).
- `docker-compose.yml` — platform service wired to `.env`; adjust ports,
  volumes and secrets before promoting.
- `.env.example` — derived from the active stack; copy to `.env` and
  populate any `${{ENV_VAR}}` placeholders.
- `nginx.conf` — reference TLS terminator (delete if you use another
  reverse proxy or terminate TLS in the platform via
  `--ssl-certfile` / `--ssl-keyfile`).

## Quick start

```bash
cp .env.example .env
# ...populate secrets in .env, then:
docker compose up -d --build
```

## Reconciling with the repo-root Dockerfile

The repository ships a canonical `Dockerfile` and `Dockerfile.distroless`
at the project root.  This generator produces functionally equivalent
files tailored to the active stack; when in doubt, diff the two and keep
them in sync so image behaviour is predictable.
"""
